### ISSUE TITLE
Way cool!

### ISSUE THREAD

**Issue by brianegan** [letsar/flutter_staggered_grid_view#1]
Not an issue, just a big thumbs up :) I switched out a SliverGridView in favor of this library to have a bit of fun on a sample app, and got something pretty dang snazzy up and running in about 30 minutes!

Wanted to say thanks for the library, really well done!

![staggered_list4](https://user-images.githubusercontent.com/126604/36402881-a94cba82-15e1-11e8-8035-56166942b0b6.gif)

**Comment by letsar** [comment]
Thanks :blush:.
