### ISSUE TITLE
Jumping while scrolling

### ISSUE THREAD

**Issue by rdev-software** [letsar/flutter_staggered_grid_view#101]
I have dynamic list of items. Items contain cached image, whilst loading there is circular progress view. Once is loaded, size is changed...some images are bigger than others.

Thing is that i cannot scroll now, as whole layout is broken as every item is different. But I mean thats whole point of staggered grid view

**Comment by sooxt98** [comment]
@rdev-software I'm also facing this issue. What Image widget are you using? The image without cache works perfectly tho

**Comment by sooxt98** [comment]
Similar issue here https://github.com/flutter/flutter/issues/42339

**Comment by pankajadhyapak** [comment]
I'm also facing the same issue @letsar any update on this?

**Comment by kw2019ltd** [comment]
same issue for me

**Comment by zenkog** [comment]
Me too. The scrolling somehow jump up and down and sometimes its shaking! Strange.

My code is like this:

```
StaggeredGridView.builder(
        itemCount: posts.length,
        key: PageStorageKey(widget.pageKey),
        controller: controller,
        itemBuilder: (_, index) => buildPostView(posts[index]),
        gridDelegate: SliverStaggeredGridDelegateWithMaxCrossAxisExtent(
            staggeredTileBuilder: (index) => StaggeredTile.fit(1),
            maxCrossAxisExtent: kMaxPostItemCardWidth),
      ),
```

I tried also with `StaggeredGridView.extentBuilder` but it shows the same result.

Any clue? 

Thanks

**Comment by zjamshidi** [comment]
I have the same issue. Despite I fixed the aspect ratio, when I scroll items jump and the scroll is not smooth. here is my code:
```
    var width = double.parse(item.width);
    var height = double.parse(item.height);
    return GestureDetector(
        onTap: () {
     
        },
        child: Card(
          semanticContainer: true,
          clipBehavior: Clip.antiAliasWithSaveLayer,
          child: CachedNetworkImage(
            placeholder: (context, url) =>
                AspectRatio(
                    aspectRatio: width / height,
                    child: Center(child: CircularProgressIndicator())),
            imageUrl: url,

          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10.0),
          ),
          elevation: 5,
          margin: EdgeInsets.fromLTRB(3.0, 10.0, 10.0, 10.0),
        ));
```

**Comment by sunjianan9900** [comment]
ANY UPDATE ?
This is completely unavailable

**Comment by letsar** [comment]
What is the issue here? Can I have a code sample I could just copy/paste and run?

**Comment by letsar** [comment]
Closing since no response since a while.

**Comment by DiTuStudio** [comment]
same issue for me
