### ISSUE TITLE
SliverStaggeredGrid for using in a CustomScrollView.

### ISSUE THREAD

**Issue by dnfwj** [letsar/flutter_staggered_grid_view#103]
How to use this at CustomScrollView

**Comment by dnfwj** [comment]
When I use it at CustomScrollView, there is a conflict in scrolling

**Comment by Deeplightened** [comment]
You need to disable scrolling ability of the SliverStaggeredGrid by setting parameter `shrinkWrap` to true

**Comment by xml123** [comment]
I had the same problem

**Comment by jamesblasco** [comment]
Check this example on how to use SliverStaggeredGrid inside a CustomScrollView
https://github.com/letsar/flutter_staggered_grid_view/blob/master/example/lib/example_4.dart
