### ISSUE TITLE
The list of items moves from the right to the left position

### ISSUE THREAD

**Issue by mimdudin** [letsar/flutter_staggered_grid_view#110]
Hello **Team,**

previously appreciated developing this plugin.

I have a problem when I want to scroll down, where the list of items is moved from the right position to the left position.

See attachments;
![Screenshot from 2020-03-24 07-40-08](https://user-images.githubusercontent.com/29745799/77376431-e27a0b00-6da2-11ea-898e-30a2a7c4b7f1.png)
![Screenshot from 2020-03-24 07-40-09](https://user-images.githubusercontent.com/29745799/77376435-e443ce80-6da2-11ea-9ec0-1c173a415a05.png)

See the full video below;
https://drive.google.com/file/d/1vpZQvxVWcSDJ53YFLzcXYp2WUvItozXT/view?usp=sharing

**Any answer is very much appreciated**

**Comment by jamesblasco** [comment]
Hello, if the items inside the grid are using fit, maybe you wanna try to keep them alife.

See an example of how to implement it here: https://github.com/letsar/flutter_staggered_grid_view/issues/15#issuecomment-706678027

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
