### ISSUE TITLE
Flutter change StaggeredGridView crossAxisCount by screen rotation

### ISSUE THREAD

**Issue by MahdiPishguy** [letsar/flutter_staggered_grid_view#114]
`StaggeredGridView` like with `GridView` support `crossAxisCount` and that work fine when i define specific number for `crossAxisCount`, such as `1` or `2`
for this option i want to change that with screen size resolution automatically by code, for example this below code can calculate screen size and can be used for `GridView` or `StaggeredGridView`

    int _crossAxisCount = 0;
    final double screenWidthSize = MediaQuery.of(context).size.width;
    if (screenWidthSize > 720) {
      _crossAxisCount = 3;
    } else if (screenWidthSize > 520) {
      _crossAxisCount = 2;
    } else {
      _crossAxisCount = 1;
    }

when i define `_crossAxisCount` for the library `crossAxisCount` option, it doesn't work and only work when i press on hot reload button 

but when i change that to specific count, that work fine

**UPDATED:**

    LayoutBuilder(
      builder:(context,constraints){
        int _crossAxisCount = 0;
        final double screenWidthSize = MediaQuery.of(context).size.width;
        if (screenWidthSize > 720) {
          _crossAxisCount = 3;
        } else if (screenWidthSize > 520) {
          _crossAxisCount = 2;
        } else {
          _crossAxisCount = 1;
        }
        return StaggeredGridView.countBuilder(
          primary: false,
          physics: const NeverScrollableScrollPhysics(),
          shrinkWrap: true,
          crossAxisCount: 2,
          mainAxisSpacing: 2.0,
          crossAxisSpacing: 2.0,
          itemCount: feedsList.length,
          itemBuilder: (BuildContext context, int index) => Card(
              clipBehavior: Clip.antiAliasWithSaveLayer,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(8.0),
              ),
              color: Colors.white,
              child: Column(
                children: <Widget>[
                  BuildFeedsItems(
                      item: feedsList[index] as FeedsItemsList,
                      doubleTapImageEvents: _doubleTapImageEvents,
                      fullScreenDialog: fullScreenDialog,
                      theme: theme )
                ],
              )),
          staggeredTileBuilder: (index) => const StaggeredTile.fit(1),
        );
      },
    )

how can help me to know whats this issue and how can i fix that?

**Comment by uc-apa** [comment]
crossAxisCount is defined as final, and this thing is manipulated in the construtor only(SliverStaggeredGridDelegateWithFixedCrossAxisCount). So to do so we need to reload/recreate the whole widget, but then we will loose its scrollposition etc. This should be dynamic and considered in the future release of this package.
![image](https://user-images.githubusercontent.com/25792136/81906780-62269800-95e4-11ea-8d1e-61b7218581f0.png)

**Comment by MahdiPishguy** [comment]
@uc-apa is any new good news about this issue? :100:

**Comment by jamesblasco** [comment]
As @Niggelgame, for now, you can implement a key for the widget and change it every time you change the column.

The issue will be tracked in #105 

```dart
SliverStaggeredGrid.countBuilder(
              itemCount: 200,
              key: ObjectKey(columns),
              crossAxisCount: columns,
              mainAxisSpacing: 20,
              crossAxisSpacing: 10,
              itemBuilder: (BuildContext context, int index) {
                return Container(
                  color: Colors.red,
                  height: 200,
                );
              },
              staggeredTileBuilder: (int index) {
                return StaggeredTile.fit(1);
              },
            ),
```
