### ISSUE TITLE
No more updates ?

### ISSUE THREAD

**Issue by cv0cv0** [letsar/flutter_staggered_grid_view#115]
It's been a long time since I've updated.

**Comment by MahdiPishguy** [comment]
+1

**Comment by letsar** [comment]
Hello, yes I don't have a lot of free time to work on this package at the moment. Besides the dynamic resizing feature is really hard to improve, I'm even thinking about removing it (you will have to compute in advance the sizes of the tiles).

**Comment by cv0cv0** [comment]
That would be a pity, it works very well.
