### ISSUE TITLE
Staggered grid view show gray part in test flight build, working fine in android, and also iOS simulator, and iOS device when we are running it directly from xcode.

### ISSUE THREAD

**Issue by vimalgorvadia** [letsar/flutter_staggered_grid_view#118]

**Comment by jamesblasco** [comment]
Could you provide some reproducible code for this issue?

**Comment by vimalgorvadia** [comment]
Sorry for the late reply @jamesblasco, but I switched to other project during time and also by updating flutter and changing It to stable branch worked.
Thank you for your answer !
