### ISSUE TITLE
 constraints.remainingCacheExtent  and constraints.cacheOrigin

### ISSUE THREAD

**Issue by Loisgenesis** [letsar/flutter_staggered_grid_view#12]
Hello please this is my code 

 new StaggeredGridView.countBuilder(crossAxisCount: 4,
            itemBuilder: (BuildContext context, int index) => new Container(
            color: Colors.green,
            child: new Center(
              child: new CircleAvatar(
                backgroundColor: Colors.white,
                child: new Text('$index'),
              ),
            )), staggeredTileBuilder: (int index) =>
          new StaggeredTile.count(2, index.isEven ? 2 : 1),
          mainAxisSpacing: 4.0,
          crossAxisSpacing: 4.0,),

But anytime i run it it throws an error in 'package:flutter_staggered_grid_view/src/rendering/sliver_staggered_grid.dart': error: line 254 pos
and writes 
The following _CompileTimeError was thrown during performLayout():
Error: The getter 'cacheOrigin' isn't defined for the class '#lib1::SliverConstraints'.
Error: The getter 'remainingCacheExtent' isn't defined for the class '#lib1::SliverConstraints'.
Any Idea how to fix this.
Thanks

**Comment by letsar** [comment]
Hi @Loisgenesis, that's strange 🤔  . Can you post the `flutter doctor` results here?
These properties are defined in the Flutter part, so unless they changed this, you should not have these errors.

**Comment by Loisgenesis** [comment]
Hi @letsar here is my result from flutter doctor

/Users/loisgenesis/flutter/bin/flutter --no-color doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v0.3.6-pre.7, on Mac OS X 10.13.3 17D102, locale en-NG)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.2)
    ✗ libimobiledevice and ideviceinstaller are not installed. To install, run:
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.0)
[✓] VS Code (version 1.24.1)
[✓] Connected devices (1 available)

! Doctor found issues in 1 category.
Process finished with exit code 0

Nothing from here seems to be linked to the above error i'm getting

**Comment by letsar** [comment]
You are on the master channel but with an old version. Can you upgrade to the last commit or change to the beta channel which is more stable?

**Comment by Loisgenesis** [comment]
Oh ok thanks @letsar , I will let you know if that solves the issue

**Comment by Loisgenesis** [comment]
@letsar it worked after I change it to the beta channel, thanks a lot.
