### ISSUE TITLE
Adaptive high network image interface refresh is not smooth

### ISSUE THREAD

**Issue by XyliaYang** [letsar/flutter_staggered_grid_view#120]
If I want to implement an adaptive height control, the picture in the control is obtained by network request, if there is a delay, the whole picture will have the phenomenon of jumping and holding on, how to solve this.

**Comment by zhangweiwei0326** [comment]
There is also this confusion, I do not know how to solve

**Comment by jpainam** [comment]
hi @XyliaYang i think you can solve it as proposed here #143 . Save the image ratio (height/width) and pull these information with an API.
