### ISSUE TITLE
Unnecessary Rebuild

### ISSUE THREAD

**Issue by Er-Dong-Chen** [letsar/flutter_staggered_grid_view#122]
For example: after the waterfall flow list enters the detail page and returns, the waterfall flow list is redrawn, and the list is reloaded and rendered

**Comment by agubha** [comment]
having the same issue, after it reloads. the scroll position gets updated, how did you solve this issue? @MeuJia

**Comment by jamesblasco** [comment]
Could you provide some reproducible code for this issue?

**Comment by ali9653** [comment]
> For example: after the waterfall flow list enters the detail page and returns, the waterfall flow list is redrawn, and the list is reloaded and rendered

Did you find any solution?

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by kerberjg** [comment]
Keeps happening in 0.6.1

I use a MasonryGridView.count() to display a list of images loaded from the network (using a CachedNetworkImage) but every time I scroll the layout jumps all over the place as images are loaded/unloaded

```dart
MasonryGridView.count(
            addAutomaticKeepAlives: true,
            cacheExtent: 200.0,
            crossAxisCount: 2,
            mainAxisSpacing: 4,
            crossAxisSpacing: 4,
            itemCount: stuff.length,
            itemBuilder: (context, index) {
              debugPrint('Item build: $index');
              return MAT.Image.network(
                  stuff[index]['imageHighUrl'], stuff[index]['thumbnailData']);
            },
          );
```

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
