### ISSUE TITLE
SliverStaggeredGrid ScrollController

### ISSUE THREAD

**Issue by chiragmittal19** [letsar/flutter_staggered_grid_view#123]
It'll be good to have a `ScrollController` applicable on `SliverStaggeredGrid`. It'll give us the ability to add pagination, and also jump/scroll to position.

**Comment by jamesblasco** [comment]
You can control the scroll of the `SliverStaggeredGrid` through the param `controller` of the `CustomScrollView`.

The `SliverStaggeredGrid` itself it is not scrollable, in needs to be added to a scroll view
