### ISSUE TITLE
Doesn't Fill In Gaps

### ISSUE THREAD

**Issue by zgosalvez** [letsar/flutter_staggered_grid_view#124]
Using [example_1.dart](example/lib/example_1.dart), replace `_staggeredTiles` with:

```dart
  const StaggeredTile.count(1, 1),
  const StaggeredTile.count(2, 1),
  const StaggeredTile.count(1, 1),
  const StaggeredTile.count(2, 2),
  const StaggeredTile.count(1, 1),
  const StaggeredTile.count(2, 1),
  const StaggeredTile.count(2, 2),
  const StaggeredTile.count(1, 1),
  const StaggeredTile.count(1, 1),
  const StaggeredTile.count(4, 1),
```

You'll get a grid that has a gap. I don't know how I can make the 1x1 tile at the bottom fill the gap. 
![Simulator Screen Shot - iPad Air (3rd generation) - 2020-06-23 at 20 16 19](https://user-images.githubusercontent.com/1798166/85402644-9b143e00-b58e-11ea-8c1d-81f32ea54f37.png)
My actual use case will use dynamic data that has already been sorted, but the grid has to fit all of the tiles even if it will be slightly unsorted. 
![Simulator Screen Shot - iPad Air (3rd generation) - 2020-06-23 at 20 05 29](https://user-images.githubusercontent.com/1798166/85402986-33aabe00-b58f-11ea-8874-fc911822ae2c.png)
The arrangement is ok, but tile "H" still fits beside "E".

**Comment by joshuadeguzman** [comment]
Hey @zgosalvez,

You can try `StaggeredGridView.extent` or for your case, it's `StaggeredGridView.extentBuilder` for displaying dynamic data.

More on the implementation details can be found here:
https://github.com/joshuadeguzman/flutter_staggered_grid_view-repro-124

I extracted most of it from [this](https://github.com/letsar/flutter_staggered_grid_view/blob/master/example/lib/staggered_extent_count_page.dart) and added your data.

After reading and checking how this plugin renders tiles, this is the most suitable to use in your case without you having to sort tiles prior to rendering to fill in gaps.

**Comment by zgosalvez** [comment]
I tried that but it didn't work well with larger extents, it behaved the same way as `count`. You can see this on a small screen, by changing `maxCrossAxisExtent: 200,` or setting `crossAxisCount: 2,`

From your screenshot, it appears that each row occupies 3 columns, but I need it to only occupy 2. My use case requires a fixed count per row, which was why I used `count` initially. As you can see here, it doesn't fill in the gaps.

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-07-03 at 14 14 36](https://user-images.githubusercontent.com/1798166/86437660-89255e80-bd37-11ea-92f1-048e939237c1.png)

I tried using `extent` and specified that it would fit the 2 tiles in the row using LayoutBuilder's `maxWidth` (See the snippet below). But in this case, it looked like your screenshot, which had 3 columns instead of 2.

```dart
return LayoutBuilder(
  builder: (BuildContext context, BoxConstraints constraints) {
    return StaggeredGridViewPage.extent(
        title: 'Staggered (Extent, Count)',
        maxCrossAxisExtent: ((constraints.maxWidth - 16) / 2), // available width less spacings over number of columns
        // crossAxisCount: 2,
        tiles: _tiles);
  },
);
```

**Comment by joshuadeguzman** [comment]
Hi Zennon, 

Curious if you can send me a set of data that you are trying to display? I’ll play around with them and see if there’s a pattern I could found using Flutter APIs.

Didn’t know the exact number of items you’re trying to display in a row before. I might have missed something.

Thank you.

**Comment by Rahuvich** [comment]
I have a similar bug, but with `.count()` constructor.
```dart
StaggeredGridView.count(
          physics: NeverScrollableScrollPhysics(),
          shrinkWrap: true,
          padding: EdgeInsets.symmetric(vertical: padding, horizontal: padding),
          crossAxisSpacing: padding,
          mainAxisSpacing: padding,
          crossAxisCount: bigCards ? 2 : 3,
          children: list,
          staggeredTiles: List.generate(list.length, (int index) {
            if (list[index] is InfoCard && (list[index] as InfoCard).big) {
              return StaggeredTile.fit(2);
            } else
              return StaggeredTile.fit(1);
          })),
```
I would expect the grid to fill the rows from left to right, but it doesn't.
![Captura de pantalla 2020-08-13 a las 17 58 12](https://user-images.githubusercontent.com/20211760/90157997-b598b580-dd8e-11ea-975a-61504a8785d6.png)

**Comment by letsar** [comment]
Yes this is how the algorithm works. I don't plan to change it for the moment.
