### ISSUE TITLE
Use bigger height as height for all items in the same row. (Same for width/column when AxisDirection.horizontal)

### ISSUE THREAD

**Issue by enricobenedos** [letsar/flutter_staggered_grid_view#125]
Good morning,
I'm trying this package due to a problem related to Flutter `GridView` aspect ratio that not permit me to show a responsive card on different devices.
Using this package is it possible to define that all items inherit height from the higher item?

Thanks

**Comment by jamesblasco** [comment]
No, it is not possible for now. This would be very expensive to calculate.

You can add predefined heights or that each element fits the size of the cell.

**Comment by jamesblasco** [comment]
Duplicate of https://github.com/letsar/flutter_staggered_grid_view/issues/76
