### ISSUE TITLE
Unhandled Exception: type 'SliverHitTestResult' is not a subtype of type 'BoxHitTestResult'

### ISSUE THREAD

**Issue by bharat8** [letsar/flutter_staggered_grid_view#126]
Hello everyone!

So, I tried using Example08 of this project in my own project and after launching the app in my emulator, the grid-view is created fine but the problem is that I am not able to scroll the Screen and the above error is keep on flashing every-time I Scroll the screen down.

Can anyone suggest a solution?

**Comment by ninjaasmoke** [comment]
Check #49

**Comment by jamesblasco** [comment]
@bharat8 Could you confirm that using version 0.3.0 fixed your problem?
