### ISSUE TITLE
Is it possible to remove the shadow below each grid ?

### ISSUE THREAD

**Issue by Linspirit98** [letsar/flutter_staggered_grid_view#127]
I am using StaggeredGridView.countBuilder and I am passing card widget to itembuilder. However there is some elevation/shadow below each card. 
itemBuilder: (context, index) => Card()

Is there a way of removing the shadow without using container?
Thanks

**Comment by heath3n** [comment]
You mean like the `elevation` property in the `Card` widget?

**Comment by Linspirit98** [comment]
> You mean like the `elevation` property in the `Card` widget?

yes. I also figured that. Thank you!
