### ISSUE TITLE
Last row should not add spacing

### ISSUE THREAD

**Issue by huajianjiang** [letsar/flutter_staggered_grid_view#130]
Last mainAxisSpacing should 0, follow official GridView.

**Comment by felipecastrosales** [comment]
SliverStaggeredGrid.count(
                    crossAxisCount: 2,
                    mainAxisSpacing: 4.0,
                    crossAxisSpacing: 4.0,
                    staggeredTiles: snapshot.data.documents.map((doc) {
                      return StaggeredTile.count(doc.data['x'], doc.data['y'])

**Comment by jamesblasco** [comment]
Reproducible example: 
```dart

CustomScrollView
          slivers: <Widget>[
            SliverStaggeredGrid.countBuilder(
              itemCount: 200,
              crossAxisCount: 5,
              mainAxisSpacing: 20,
              crossAxisSpacing: 10,
              itemBuilder: (BuildContext context, int index) {
                return Container(
                  color: Colors.red,
                  height: 200,
                );
              },
              staggeredTileBuilder: (int index) {
                return StaggeredTile.fit(1);
              },
            ),
          ]
      );

```

**Comment by pbozzay** [comment]
Still repro's, this is a pretty frustrating issue when trying to style a container or border around the entire grid view.

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
