### ISSUE TITLE
I am getting this, do you know how I am wrong ? @@

### ISSUE THREAD

**Issue by dinhan1192** [letsar/flutter_staggered_grid_view#131]
![image](https://user-images.githubusercontent.com/42635147/89516661-efa00f80-d802-11ea-8e55-b1fe37af5576.png)
![image](https://user-images.githubusercontent.com/42635147/89516724-ff1f5880-d802-11ea-8c03-aaf8d14a0ab7.png)

**Comment by agnamc9** [comment]
Can you share the code of your ```listInside(...)``` ?

**Comment by jamesblasco** [comment]
Please add some reproducible code of this issue so we can help you

**Comment by letsar** [comment]
Closing since no answer
