### ISSUE TITLE
No material widget found when implement load more in scroll

### ISSUE THREAD

**Issue by alfaben12** [letsar/flutter_staggered_grid_view#134]
<img width="307" alt="Screen Shot 2020-09-15 at 11 27 14 AM" src="https://user-images.githubusercontent.com/20008086/93165494-6acfdc00-f746-11ea-996d-9f799fb589fb.png">

I get error
`
════════ Exception caught by rendering library ═════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3523 pos 12: 'child._parent == this': is not true.
The relevant error-causing widget was
    StaggeredGridView 
`
when add data to list (load more)

**Comment by jamesblasco** [comment]
Could you provide a reproducible code for this issue? 

It looks like a cell inside that requires a Material widget and you don't have any inside the widget tree. The error doesn't look related to this package

**Comment by letsar** [comment]
No response, and not related to that pacakge
