### ISSUE TITLE
Countbuilder adds some divider lines when spacing is 0

### ISSUE THREAD

**Issue by dzsonni** [letsar/flutter_staggered_grid_view#135]
Flutter doctor:
[√] Flutter (Channel master, 1.23.0-8.0.pre.27, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.23.0-8.0.pre.27 at D:\Development\flutter
    • Framework revision 8db31a556b (6 days ago), 2020-09-28 14:32:00 +0200
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at D:\Development\AndroidSDK
    • Platform android-30, build-tools 30.0.2
    • Java binary at: D:\Development\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at D:\Development\AndroidStudio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

When creating a grid with count I see some lines between certain tiles, my guess is this is something that has to do with rounding.
![image](https://user-images.githubusercontent.com/6988242/95025023-5e78d800-068f-11eb-8625-4cc4387369da.png)
Any ideas how to fix?

**Comment by Darth-Carrotpie** [comment]
This is also bugging me. So annoying to see them, feels like the app is buggy when you can see only some lines but not all of them. At least it would be consistent....

**Comment by letsar** [comment]
I think it's an issue with double precision.
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1
Also, you can try to fix it be setting a fixed width which would be divisible by the number of columns.

**Comment by dzsonni** [comment]
@letsar Hey, this is a bit of an old issue, I think I solved it back then with building some custom fields. But during the following month I need to use something similar in another project so I will get back to you.

**Comment by letsar** [comment]
@dzsonni do you still encounter this issue ?

**Comment by letsar** [comment]
Closing since no response since a while.
