### ISSUE TITLE
Scrolling continuously and at one scroll reaching top when I set tile to fit

### ISSUE THREAD

**Issue by benevolent13** [letsar/flutter_staggered_grid_view#139]
I face an issue with scrolling, first it scroll normally then it scroll so fast and doesn't stop till the end and scrolling up take me to top of the page at one little scroll so odd when I set staggeredTile.fit

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
