### ISSUE TITLE
SliverGridGeometry doesn't accept null arguments anymore

### ISSUE THREAD

**Issue by mdebbar** [letsar/flutter_staggered_grid_view#140]
During Flutter's migration to null-safety, the constructor of `SliverGridGeometry` [stopped accepting null values](https://github.com/flutter/flutter/blob/8a6a76a33450c956ae5ac1788b1cae07af3e8244/packages/flutter/lib/src/rendering/sliver_grid.dart#L28-L31).

But the `SliverStaggeredGridGeometry` class in this package is still accepting null values and [passing them](https://github.com/letsar/flutter_staggered_grid_view/blob/efb9235e908d51d5bc6e52dc17b5547a2e89b529/lib/src/rendering/sliver_staggered_grid.dart#L145) to `SliverGridGeometry`. This is causing errors to be thrown when running in null-safe mode.

**Comment by letsar** [comment]
Thank you, can you tests with the null safety pre-release?

**Comment by letsar** [comment]
Closing since no response
