### ISSUE TITLE
Swipe up/down not working when placed in Pageview

### ISSUE THREAD

**Issue by garlicgit** [letsar/flutter_staggered_grid_view#141]
I'm using this widget inside of Pageview. When I swipe up/down Pageview does not recognized my intent, in just thinks I am scrolling up/down. Is there anything in flutter_staggered_grid_view that might help me with this issue?

TIA.

**Comment by tomake** [comment]
I have meet the same issue and try to fix it by changing touch event, but flutter widget does not offer entrance to intercept  touch event .  Is there any resolution?

**Comment by letsar** [comment]
Not linked to that package
