### ISSUE TITLE
scrolling is not smooth with StaggeredTile.fit when data is fetch online

### ISSUE THREAD

**Issue by jpainam** [letsar/flutter_staggered_grid_view#143]
Hi, When fetching data online and using a variable extent, defined by the content of the tile itself =>  StaggeredTile.fit. the scrolling is not smooth, as the sizes are built as the images arrived.

Do you have any good idea on how to solve this problem? Maybe hard code the image size and use a fixed staggeredTile size instead of the variable extent.

**Comment by SergejSachs** [comment]
I have the same performance problem, feels like its calculating while scrolling all the time.

**Comment by alchalade** [comment]
I had a similar issue. 
In my case, my advantage was that I pulled the images from my own server.  Therefore, I was able to store the dimension ratio and passed it in the API response.

**Comment by jpainam** [comment]
@alchalade I think this is the best way to do it. thanks.
