### ISSUE TITLE
Making Grid items in Staggered View draggable and reordering grid items on drop.

### ISSUE THREAD

**Issue by zihandev** [letsar/flutter_staggered_grid_view#144]
Can the grid items rendered using staggered grid view builder method be draggable. I did give it a try using draggable widget, but on drag getting wrong indexes of few drag-target grid item from builder method, and hence the reordering of grid items after drop is not proper.

Attached is code snippet for your reference. 

 body: new Padding(
            padding: const EdgeInsets.only(top: 12.0),
            child: StaggeredGridView.countBuilder(
              crossAxisCount: 3,
              itemCount: myList.length,
              staggeredTileBuilder: (int index) => _staggeredTiles[index],
              itemBuilder: (BuildContext context, int index) => new Container(
                child: isDragging
                    ? DragTarget(
                        builder:
                            (context, List<int> candidateData, rejectedData) {
                      
                          return Opacity(opacity: .8, child: myList[index]);
                        },
                        onAccept: (_dragData) {
                          print('$_dragData _dragData $index');
                       
                          setState(() {
                            isDragging = false;
                            var tempValue = myList[index];
                            myList[index] = myList[_dragData];
                            myList[_dragData] = tempValue;
                          });
                        },
                      )
                    : Draggable(
                        data: index,
                        onDragStarted: () {
                          setState(() => isDragging = true);
                        },
                        feedback: myList[index],
                        onDraggableCanceled: (_, __) {                        
                          setState(() => isDragging = false);
                        },
                        child: myList[index]),
              ),
              mainAxisSpacing: 4.0,
              crossAxisSpacing: 4.0,
              padding: const EdgeInsets.all(4.0),
            )));

**Comment by sendhav05** [comment]
Hi @zihandev did you get any solution?

**Comment by qq1023308356** [comment]
https://pub.flutter-io.cn/packages/drag_anim  can use this

**Comment by letsar** [comment]
Dupllicates #3 #80

**Comment by CrypticVader** [comment]
> https://pub.flutter-io.cn/packages/drag_anim can use this

Thanks for this
