### ISSUE TITLE
Having multiple SliverStaggeredGrids causes snapping list

### ISSUE THREAD

**Issue by tristan-vrt** [letsar/flutter_staggered_grid_view#145]
When using multiple SliverStaggeredGrids in a CustomScrollView it causes the list to scroll up once you scroll past the first list. Example:
`CustomScrollView(
          slivers: <Widget>[
            SliverStaggeredGrid.countBuilder(
              crossAxisCount: 2,
              staggeredTileBuilder: (_) => StaggeredTile.fit(1),
              itemBuilder: (context, index) => ProductGridItem(
                products[index],
              ),
              itemCount: products.length,
            ),
            SliverStaggeredGrid.countBuilder(
              crossAxisCount: 2,
              staggeredTileBuilder: (_) => StaggeredTile.fit(1),
              itemBuilder: (context, index) => ProductGridItem(
                products[index],
              ),
              itemCount: products.length,
            ),
          ],
        )`

It looks like, when the first SliverStaggeredGrid has been scrolled out of screen, it will still trigger a rebuild with zero scrollExtend. This makes the CustomScrollView snap to the first position of the first SliverStaggeredGrid and afterwards scroll back down the remaining scrolling pixels.

**Comment by ingmferrer** [comment]
any fix?

**Comment by letsar** [comment]
@ingmferrer any sponsoring?

**Comment by xiaoluokai** [comment]
I have the same issus, when I push another view the scrollview will scroll to top,

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by xiaoluokai** [comment]
您好，您发的邮件我已经受到了，我会尽快查看的。                                                            骆锴

**Comment by letsar** [comment]
In english please

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.

**Comment by xiaoluokai** [comment]
您好，您发的邮件我已经受到了，我会尽快查看的。                                                            骆锴
