### ISSUE TITLE
StaggeredGridView.countBuilder performance 

### ISSUE THREAD

**Issue by Sesa1988** [letsar/flutter_staggered_grid_view#146]
Hi,

I have performance issues while scrolling. 
My grid contains like 30 items. 

Do some of you had fixed somehow this issue. 
Probably its deeper at this lib.

**Comment by SunnyDayDev** [comment]
I faced this issue too.
I notiсed that the scroll gets slower progressively,  the further the slow. Scrolling gets better when moving back to the top.

**Comment by ali9653** [comment]
Same issue, I'm fetching images from an API. After 50-60 images it becomes laggy. Have you found any solution yet?

**Comment by SunnyDayDev** [comment]
Not yet. I'll try to find time during the holidays and fix the issue if I can.

**Comment by shliama** [comment]
Facing the same issue. Most probably it's related to using `StaggeredTile.fit(1)` and, therefore, this issue https://github.com/letsar/flutter_staggered_grid_view/issues/113

There is already a fork containing a fix, but who know, whether it's properly done. @letsar could you check it out and merge into fresh release?

**Comment by SunnyDayDev** [comment]
@shliama 
At first glance, the mentioned solution works fine but it's not quite a true. The solution can lead to the OutOfMemory error. This is especially true for very long or infinite lists. Anyway, thanks for the mention, it might help me find the right solution.

**Comment by SergejSachs** [comment]
> I faced this issue too.
> I notiсed that the scroll gets slower progressively, the further the slow. Scrolling gets better when moving back to the top.

yes that's exactly my experience as well

**Comment by ali9653** [comment]
Any fix yet?

**Comment by ingmferrer** [comment]
any fix?

**Comment by SunnyDayDev** [comment]
Unfortunately no. I tried to fix, but the attempt was unsuccessful.
Currently, I changed the project so I'm not sure if I'll try again.

**Comment by alevinetx** [comment]
@SunnyDayDev Did you try using the .builder constructor?

```This constructor is appropriate for grid views with a large (or infinite) number of children because the builder is called only for those children that are actually visible.```

I know 30 isn't large, but I'm trying to resolve app crashing with seemingly >20 (I can't replicate, waiting to hold the physical device it's crashing on).  I'm trying to work my way through the levels of the ctor and StaggeredTile, and getting a bit lost in the process.  My brain could just be done for the day at this point.

**Comment by SunnyDayDev** [comment]
@alevinetx Yes. I used the .countBuilder constructor, it's the same but with the siplified gridDelegate creation.

**Comment by alevinetx** [comment]
I somehow missed that they were variants, and was hoping this would be the silver bullet. 

I'm not sure what's deciding "on demand", as I see the builder being called for my entire list before it's rendered.  Without knowing dimensions ahead of time, there's only so much magic that can be done.

**Comment by shliama** [comment]
Maybe we can keep a map of grid item sizes, so when the Grid is scrolled, there is no need to re-render previous items (just to calculate the offset). Logic may become complex if grid items can be updated (items order changes, or items size changes).

**Comment by rmControls** [comment]
Any Solution for this ??
I almost completed my project, but now at the time of final test I realized this lag issue......

**Comment by HiroshiHorie** [comment]
I realized I'm having this issue also... any work arounds for the mean time ?

**Comment by Azzeccagarbugli** [comment]
I found out that in a Flutter web application the issue is even more visibile, the items are literally making the whole interface lagging

**Comment by frankyvij** [comment]
Unless this issue is resolved, I need to continue to use GridView instead.. I wonder why won't it be supported by this plugin, lazy loading is the most basic that widgets like this should offer. Isn't it?

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.

**Comment by CodeWithKamal** [comment]
Still having performance issues, very laggy experience.
