### ISSUE TITLE
keepAlive

### ISSUE THREAD

**Issue by pangoo-reuse** [letsar/flutter_staggered_grid_view#15]
when scroll to another page,and back ,but the child auto scroll to top ,like below  

`new StaggeredGridView.count(
          crossAxisCount: 3,
          mainAxisSpacing: 4.0,
          crossAxisSpacing: 4.0,
          padding: const EdgeInsets.all(4.0),
          addAutomaticKeepAlives: true,
          addRepaintBoundaries: true,
          scrollDirection: Axis.vertical,
          children: []
)`

please tell me how do we do ?

thanks!

**Comment by letsar** [comment]
Hi @YoneHsiung,

Can you write a complete solution that I would just have to copy/paste to test it please?
I had to rewrite everything about `KeepAlive` because of https://github.com/flutter/flutter/pull/19380, and  this PR might help me to fix things related to KeepAlives.
I will wait for it to be merged in order to dive deeper in this issue.

**Comment by jzoom** [comment]
This is what I'am searching for , thank you for your `KeepAlive`.

**Comment by JacenWei** [comment]
@letsar  I also encountered the same problem in the process of using it. What should I do?  thanks!

**Comment by nishanthrk** [comment]
addAutomaticKeepAlives is true by default to make it work you need to extend AutomaticKeepAliveClientMixin and

@override
bool get wantKeepAlive => true;

@override
  Widget build(BuildContext context) {
    super.build(context);
    return Wiget;
  }

**Comment by jamesblasco** [comment]
I tried and @nishanthrk solutions work as expected

**Comment by jamesblasco** [comment]
An example of a widget with this mixin

```dart

class Counter extends StatefulWidget {
  @override
  _CounterState createState() => _CounterState();
}

class _CounterState extends State<Counter> with AutomaticKeepAliveClientMixin {
  int counter = 0;

  @override
  Widget build(BuildContext context) {
    super.build(context);

    return Material(
      child: InkResponse(
        onTap: () {
          setState(() {
            counter += 1;
          });
        },
        child: Container(
          height: 200,
          width: 200,
          child: Text('$counter'),
        ),
      ),
    );
  }

  @override
  bool get wantKeepAlive => true;
}

```
