### ISSUE TITLE
No named parameter with the name 'restorationId'

### ISSUE THREAD

**Issue by mohmdezeldeen** [letsar/flutter_staggered_grid_view#150]
when build app this error appear: No named parameter with the name 'restorationId'
Full: 
/Pub/Cache/hosted/pub.dartlang.org/pub_cache-0.2.3/hosted/pub.dev/flutter_staggered_grid_view-0.3.3/lib/src/widgets/staggered_grid_view.dart:425:11: Error: No named parameter with the name 'restorationId'.
          restorationId: restorationId,
          
this error appear after new update of package flutter_staggered_grid_view to 0.3.3
Add support for state restoration.

i used
dependency_overrides:
  flutter_staggered_grid_view: 0.3.2

**Comment by jerfsonsilva** [comment]
Eu resolvi colocar como dependencia:   flutter_staggered_grid_view: 0.3.0
assim parou de dar erro

**Comment by letsar** [comment]
What flutter version do you use?

**Comment by mohmdezeldeen** [comment]
@letsar Sorry for creating this issue here by mistake, instead of creating it in the **flappy_search_bar** repo that relies on your package, thanks for your understanding.

**Comment by joshuaatencia** [comment]
i have same error

**Comment by uzairleo** [comment]
i am facing the same error

**Comment by wjx1018960145** [comment]
请问这个问题怎么解决

**Comment by letsar** [comment]
The last version of the package is sync with the stable channel, so you should either upgrade your version of flutter (to target the current stable with` flutter upgrade`) or downgrade the version of this package.

**Comment by quanjin24k** [comment]
resolution:
1. upgrade flutter -> latest,  stage_grid_view -> your current used version;
2. or, use your current flutter version,  degrade stage_grid_view ->0.3.2;
because attribute "restorationId", is not exist in older flutter version.

**Comment by ITmxs** [comment]
flutter_staggered_grid_view: 0.3.2
