### ISSUE TITLE
Circular Progress Indicator

### ISSUE THREAD

**Issue by Pushan-Gupta** [letsar/flutter_staggered_grid_view#16]
I use your library for infinite scrolling while it fetches data from the server.

It works awesome but I found 2 specific issues.

1. I am unable to put a circular indicator while the data is being loaded as I cannot seem to find a footer in your library

2. A blank space is temporarily created for the images that are fetched from the server but not rendered in the application. This may be because as the server responds, ItemCount gets immediately updated but image uris take a bit of time.

```
  @override
  Widget build(BuildContext context) {
    var staggeredView = new StaggeredGridView.countBuilder(
      crossAxisCount: 4,
      physics: const BouncingScrollPhysics(),
      itemCount: _total,
      itemBuilder: (BuildContext context, int index) {
        Data data = _getData(index);
        String full_name = data.name;

        if (data.path != null) {
          return new GestureDetector(
            child: new Container(
                height: 200.0,
                child: new Image.network(
                  (<----------my uri------------->),
                  fit: BoxFit.cover,
                  scale: 1.0,
                )),
            onTap: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                    builder: (context) => (ViewImage.ViewImage(
                        (<----------my path------------->),
                        data.id,
                        data.comments,
                        data.likes,
                        data.views,
                        data.username,
                        data.description,
                        data.title))),
              );
            },
          );
        }
      },
      staggeredTileBuilder: (int index) =>
          new StaggeredTile.count(2, index.isEven ? 2 : 1),
      mainAxisSpacing: 4.0,
      crossAxisSpacing: 4.0,
    );
```

**_Update_**

I got around doing the progress indicator thing but I strongly feel that there should be a footer support to make it even better. 

My workaround is as soon as we reach the last index, compare it with the itemcount and then return a progress indicator.

```
itemBuilder: (BuildContext context, int index) {
        if (index == data.length - 1) {
          return new Center(
              child: new SpinKitThreeBounce(
            color: Colors.green[300],
            size: 20.0,
          ));
        } else {
          //Image here
       }
}
```

I also fixed the temporary blank space that was being created. Just pass the correct itemCount. Do not keep it null else it will become an infinite grid

**Comment by jamesblasco** [comment]
Looks like your solve your problem.

Like the flutter GridView and ListView this package lets you easily to create a footer as you did use the last index.
