### ISSUE TITLE
StaggeredGridView.countBuilder loads all elements from Streambuilder

### ISSUE THREAD

**Issue by awaik** [letsar/flutter_staggered_grid_view#161]
Hello,

Is it expected behavior that `StaggeredGridView.countBuilder` loads all the data from Streambuilder, even if it has 5000 elements?

For example, if we use the same Streambuilder with `Listview.builder` - it loads only visible + 2-3 elements further. If we scroll it will load new elements dynamically.

**Comment by awaik** [comment]
I see the same question here
https://stackoverflow.com/questions/58675132/lazy-loading-with-staggered-grid-view-in-flutter

**Comment by frankyvij** [comment]
Hello - is there any update around this?

**Comment by frankyvij** [comment]
Wow! It seems lazy loading is not even a thing for this plugin. That stackoverflow question is open since 2019.

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
