### ISSUE TITLE
Adding overflow property to Text in a Staggered Grid View throws exception

### ISSUE THREAD

**Issue by hannahgrinton** [letsar/flutter_staggered_grid_view#162]
Thought this was a Flutter bug (https://github.com/flutter/flutter/issues/76709), but after doing some digging, realized this exception only happens when using the Staggered Grid View plugin. Not sure exactly what the reason is, but as soon as I remove the overflow: TextOverflow.ellipsis from the Text widget, the error goes away. Also, it should be noted that this issue only occurs when there are enough grid items to need to scroll down the page and that there is no visible error on the device screen, only what appears in the console. I've attached the pubspec.yaml and main.dart that I used to recreate this issue in my minimal code sample.
[flutter.zip](https://github.com/letsar/flutter_staggered_grid_view/files/6044005/flutter.zip)

Here's the error:

flutter: The following assertion was thrown during a scheduler callback:
flutter: Updated layout information required for RenderIndexedSemantics#4289d NEEDS-LAYOUT NEEDS-PAINT to
flutter: calculate semantics.
flutter: 'package:flutter/src/rendering/object.dart':
flutter: Failed assertion: line 2647 pos 12: '!_needsLayout'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2647:12)
flutter: #3      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #4      Iterable.forEach (dart:core/iterable.dart:283:30)
flutter: #5      RenderSliverVariableSizeBoxAdaptor.visitChildren (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:294:29)
flutter: #6      RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #7      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #8      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #9      RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #10     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #11     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #12     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #13     Iterable.forEach (dart:core/iterable.dart:283:30)
flutter: #14     RenderViewportBase.visitChildrenForSemantics (package:flutter/src/rendering/viewport.dart:219:10)
flutter: #15     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #16     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #17     RenderIgnorePointer.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:3127:14)
flutter: #18     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #19     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #20     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #21     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #22     RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4456:11)
flutter: #23     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #24     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #25     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #26     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #27     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #28     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #29     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #30     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #31     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #32     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #33     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #34     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #35     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #36     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #37     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #38     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #39     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #40     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #41     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #42     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #43     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #44     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #45     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #46     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #47     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #48     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #49     ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3325:14)
flutter: #50     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #51     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #52     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #53     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #54     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #55     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #56     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #57     RenderIgnorePointer.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:3127:14)
flutter: #58     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #59     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #60     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #61     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #62     RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4456:11)
flutter: #63     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #64     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #65     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #66     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #67     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #68     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #69     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #70     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #71     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #72     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #73     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #74     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #75     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #76     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #77     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #78     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #79     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #80     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #81     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #82     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #83     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #84     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #85     ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3325:14)
flutter: #86     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #87     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #88     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #89     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #90     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #91     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #92     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #93     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #94     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #95     RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #96     RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #97     RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #98     RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #99     RenderSemanticsAnnotations.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:4456:11)
flutter: #100    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #101    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #102    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #103    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #104    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #105    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #106    RenderIgnorePointer.visitChildrenForSemantics (package:flutter/src/rendering/proxy_box.dart:3127:14)
flutter: #107    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #108    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #109    ContainerRenderObjectMixin.visitChildren (package:flutter/src/rendering/object.dart:3325:14)
flutter: #110    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #111    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)
flutter: #112    RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2669:61)
flutter: #113    RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3042:14)
flutter: #114    RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2754:5)
flutter: #115    RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2664:5)

**Comment by vHanda** [comment]
Slighter smaller example which reproduces the problem -

```
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(context) {
    var gridView = SliverStaggeredGrid.extentBuilder(
      itemCount: 100,
      itemBuilder: (BuildContext context, int index) {
        return Container(
          width: 200,
          height: 200,
          color: Colors.amber,
        );
      },
      maxCrossAxisExtent: 200.0,
      staggeredTileBuilder: (int i) => const StaggeredTile.fit(1),
      mainAxisSpacing: 8.0,
      crossAxisSpacing: 8.0,
    );

    var view = CustomScrollView(slivers: [gridView]);
    return MaterialApp(home: Scaffold(body: view));
  }
}
```

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
