### ISSUE TITLE
listview in gridview item can not be fully shown

### ISSUE THREAD

**Issue by jinfagang** [letsar/flutter_staggered_grid_view#165]
I have listview in everysingle gridview item. It's dynamic listview not static, and I set physics to NeverScroll, but the listview can not be fully shown.

how to do in this scenarios.

**Comment by letsar** [comment]
This doesn't look like a good idea. Why do you need a ListView in each grid tile?

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
