### ISSUE TITLE
Arabic language (right to left) not supported

### ISSUE THREAD

**Issue by moesaeed** [letsar/flutter_staggered_grid_view#17]
adding in
1- **pubspec.yaml:** 
flutter_localizations:
    sdk: flutter
2- **MaterialApp**
locale: Locale("ar"),
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],

In the main example will get all the boxes on top of each other
![screen shot 2018-10-20 at 8 46 27 pm](https://user-images.githubusercontent.com/2155564/47258803-67277200-d4a9-11e8-9a01-9ba446f35507.png)

**Comment by letsar** [comment]
Fixed in 0.2.3
