### ISSUE TITLE
框架引用会报错

### ISSUE THREAD

**Issue by shenLaiMango** [letsar/flutter_staggered_grid_view#171]
#瀑布流用的框架
  flutter_staggered_grid_view: ^0.3.0
  cached_network_image: ^2.2.0+1
sdk 1.17.3

../../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_staggered_grid_view-0.3.4/lib/src/widgets/staggered_grid_view.dart:486:11: Error: No named parameter with the name 'restorationId'.
          restorationId: restorationId,
          ^^^^^^^^^^^^^

**Comment by RicoLiu** [comment]
> #瀑布流用的框架
> flutter_staggered_grid_view: ^0.3.0
> cached_network_image: ^2.2.0+1
> sdk 1.17.3
> 
> ../../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_staggered_grid_view-0.3.4/lib/src/widgets/staggered_grid_view.dart:486:11: Error: No named parameter with the name 'restorationId'.
> restorationId: restorationId,
> ^^^^^^^^^^^^^

报错说的是 restorationId 这个参数找不到，可能是插件版本不兼容，试试降低版本
