### ISSUE TITLE
Updated layout information required for RenderIndexedSemantics

### ISSUE THREAD

**Issue by pulstar** [letsar/flutter_staggered_grid_view#174]
After updated to the latest version, I am getting the following error while scrolling the grid:

```
Updated layout information required for RenderIndexedSemantics#8a24c NEEDS-LAYOUT to calculate semantics. - during a scheduler callback (scheduler library) [2021-05-13 09:50:28]
I/flutter ( 8564): Exception: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2658 pos 12: '!_needsLayout': Updated layout information required for RenderIndexedSemantics#8a24c NEEDS-LAYOUT to calculate semantics.
I/flutter ( 8564): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
I/flutter ( 8564): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
I/flutter ( 8564): #2      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2658:12)
I/flutter ( 8564): #3      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2680:61)
I/flutter ( 8564): #4      Iterable.forEach (dart:core/iterable.dart:257:30)
I/flutter ( 8564): #5      RenderSliverVariableSizeBoxAdaptor.visitChildren (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:296:29)
I/flutter ( 8564): #6      RenderObject.visitChildrenForSemantics (package:flutter/src/rendering/object.dart:2765:5)
I/flutter ( 8564): #7      RenderObject._getSemanticsForParent (package:flutter/src/rendering/object.dart:2675:5)
I/flutter ( 8564): #8      RenderObject._getSemanticsForParent.<anonymous closure> (package:flutter/src/rendering/object.dart:2680:61)
I/flutter ( 8564): #9      RenderObjectWithChildMixin.visitChildren (package:flutter/src/rendering/object.dart:3053:14)
I/flutter ( 8564): #10     RenderObject.visitChildrenFo
```

I think this have something to do with semantics index. ListView and GridView have an addSemanticIndexes property that can be disabled to enhance performance at the cost of accessibility. Could StaggeredGridView have such option too?

By the way, I noticed that the scrolling is a bit sluggish. Can it be improved?

**Comment by Klabauterman** [comment]
same issue here

**Comment by windhamg** [comment]
I'm experiencing this issue as well.

**Comment by weiminghuaa** [comment]
same issue here

**Comment by EdsonBueno** [comment]
Same here.

**Comment by ari-borlaza** [comment]
me too, is there a fix for this?

**Comment by samdogg7** [comment]
Any updates on this issue?

**Comment by samdogg7** [comment]
I noticed this on iOS, when nesting a `SliverStaggeredGrid.countBuilder` inside a `CustomScrollView`. Originally I had my `CustomScrollView`'s physics set to `BoucingScrollPhysics`. When switching this to `ClampingScrollPhysics`, I was able to resolve the error. While this is not the ideal functionality I wished to obtain, it did resolve the issue.

**Comment by EdsonMello-code** [comment]
Any solution?

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by EdsonMello-code** [comment]
The problem was with the desktop flutter.

**Comment by letsar** [comment]
Ok so I'm closing this

**Comment by samdogg7** [comment]
@letsar this issue is occurring on an iPhone 11 Pro Max (physical device). @EdsonMello-code this is not desktop specific.
