### ISSUE TITLE
Additionnal strange padding

### ISSUE THREAD

**Issue by Sharkigamers** [letsar/flutter_staggered_grid_view#175]
Hello,

I encounter an issue by using your StaggeredGridView, a strange margin is put on top of the StaggeredGridView. I don't know why it perfectly worked before a hot reload and now it is stuck with the margin. I have cleaned all my libraries and my cache to verify if the problem doesn't came from me but nothing change.

Here the picture of the problem

![image](https://user-images.githubusercontent.com/49515579/119049955-7e140500-b9c1-11eb-9b70-91e6f27bbf14.png)

```flutter
return StaggeredGridView.countBuilder(
      scrollDirection: Axis.vertical,
      shrinkWrap: true,
      itemCount: choices.length,
      crossAxisCount: 2,
      mainAxisSpacing: 0,
      crossAxisSpacing: 0,
      itemBuilder: (BuildContext context, int index) {
            // my things
      }
      staggeredTileBuilder: (index) => StaggeredTile.fit(1),
);
```

For information the StaggeredGridView is a stful widget wrapped into a Column, so I have tried to put a text before my StaggeredGridView stful widget, and the text hasn't got margin : 

![image](https://user-images.githubusercontent.com/49515579/119050355-072b3c00-b9c2-11eb-9883-7b1cc64d91cc.png)

![image](https://user-images.githubusercontent.com/49515579/119051140-152d8c80-b9c3-11eb-827f-98c37e0d6fc3.png)

Best regards.

**Comment by Sharkigamers** [comment]
I found the problem, now it needs a fix: when you do not have an Appbar in your Scaffold the widget will add an additionnal margin depending of the size of your phone height.

**Comment by clragon** [comment]
You can give this a try:

```dart
Scaffold(
  body: MediaQuery.removeViewInsets(
    context: context,
    removeTop: true,
    child: yourChild(),
  )
);
```

Though this issue is unrelated to the staggered_grid package, 
so it would be nice if you could close it.

**Comment by ywake** [comment]
I had the same problem.
A temporary solution is use `count()` and set `padding: EdgeInsets.zero`.
```dart
return StaggeredGridView.count(
  padding: EdgeInsets.zero
  children: List.generate(choices.length, (index) {
      // your things
  }),
  staggeredTiles: List.generate(choices.length, (index) => StaggeredTile.fit(1)),
);
```

But I also want countBuilder to have a padding argument as well...

**Comment by Sharkigamers** [comment]
Fine thank you !

**Comment by jlnrrg** [comment]
Giving that one uses a `SliverAppBar`, this creates issues, that are hard to fix, as the use of a lot of the constructors do not allow to set/ override the `padding` property.
@Sharkigamers have you found out, where/ why the `padding` is set?

@letsar, please consider exposing the padding in the other constructors, till there can be a real fix for this.

**Comment by zi6xuan** [comment]
@jlnrrg 
```
MediaQuery.removePadding(
          removeTop: true,
          context: context,
          child: StaggeredGridView.countBuilder
```
Thanks,it's works for me
