### ISSUE TITLE
SliverStaggeredGrid not sorting correctly in some situations

### ISSUE THREAD

**Issue by josefrvaldes** [letsar/flutter_staggered_grid_view#176]
I've been experiencing some strange sorting behaviours. 

This is the code I'm using:

`child: SliverStaggeredGrid.countBuilder( crossAxisCount: 2, itemCount: r.length, mainAxisSpacing: 24, crossAxisSpacing: 16, staggeredTileBuilder: (int index) => const StaggeredTile.fit(1), itemBuilder: (BuildContext context, int index) { final newspaper = r[index]; return GestureDetector( onTap: () => context.pushRoute( WebViewRoute(launchUrl: newspaper.baseUrl!)), child: _Tile( newspaper.thumbnailUrl!, index, title: newspaper.date!.published!.toFormattedDate, ), ); }, ),`

It's showing two columns and that's what I'm expecting, but as the items have different heights, it shows strange sort behaviours.

![screenshot](https://user-images.githubusercontent.com/7542644/119138567-4f8a3e80-ba42-11eb-8175-a833eb1de350.png)

As you can see, neither dates nor indexes are sorted correctly in that specific layout.

This is happening to me with plugin version 0.4.0 and flutter 2.0.6 and dart 2.12.3

**Comment by henry2man** [comment]
@josefrvaldes I'm encountering the same problem as you. One would probably expect to always get the results in "natural" order, with the first item always being the leftmost item.

If you want an alternative implementation that does work in natural order try this package: https://pub.dev/packages/masonry_grid

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by ricpar11** [comment]
This issue still happens in `flutter_staggered_grid_view 0.5.0-dev.6`

I'm currently using `SliverMasonryGrid.count`

**Comment by letsar** [comment]
This is how the algorithm layout works. It places items at the minimum main axis position.

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.

**Comment by samleecampspot** [comment]
Just curious if there is a way to change the placement algorithm to do left-most first and then top-most?
