### ISSUE TITLE
WEB: tiles are destroyed when window resizing.

### ISSUE THREAD

**Issue by dadagov125** [letsar/flutter_staggered_grid_view#177]
When the window is resized, all tiles are destroyed and recreated. Is there a way to cache tiles?
Using StaggeredGridView.countBuilder.

**Comment by ajay963** [comment]
Me also facing same issue ,
Please fix this issue ASAP

**Comment by dadagov125** [comment]
Found a temporary solution.
![1](https://user-images.githubusercontent.com/21357657/119386493-26261880-bcb7-11eb-818e-c69f4c05d973.PNG)
Each time the key value changes, the grid is rebuilt. In my case, DeviceType is Mobile, Tablet and desktop, which are calculated from MediaQuery.

**Comment by ajay963** [comment]
I am unable to use staggered grid view with fit tile in null safety .

Every time giving error for null

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
