### ISSUE TITLE
SliverStaggeredGrid.countBuilder is building all widgets - terrible performance

### ISSUE THREAD

**Issue by frankyvij** [letsar/flutter_staggered_grid_view#179]
/// This constructor is appropriate for grid views with a large (or infinite)
  /// number of children because the builder is called only for those children
  /// that are actually visible.

Above comment is  as wrong as it can get, the SliverStaggeredGrid.countBuilder is building every single widget whenever the itemCount increases. This is causing a huge performance lag, and unnecessary consumption of memory.

Is this intended? If not, how do we fix it?

And if this was intended, then why put a comment like that on top of this function?

This is highly suprising for a plugin that has more than 2k stars on github. What is going on?

**Comment by ManInTheWind** [comment]
I have the same issue on my project too.and the performance is terrible when the item count get more

**Comment by BedRockGx** [comment]
Yes, I also encountered this situation. When the content increases, there will be obvious frame loss problems.
I hope the author can help solve this problem

**Comment by frankyvij** [comment]
Hi @letsar , are you still maintaining this repo? Do you have any recommendations for us?

**Comment by frankyvij** [comment]
Thanks a lot @ManInTheWind , I will take a look now and post an update on this thread...

**Comment by frankyvij** [comment]
Hi @ManInTheWind , thanks for recommending the package. Are you able to span the widget to multiple columns on the cross axis? I can only span to the main axis...

**Comment by ManInTheWind** [comment]
@frankyvij 
try NestedScrollView( scrollDirection = Axis.horizontal; ... ) 
it's easy to get what u want

**Comment by vantrung8794** [comment]
Memory does not decrease with a large list. I tried SliverStaggeredGrid.builder and SliverStaggeredGrid.countBuilder with a large number of tiles. When I scroll, the old item in the grid which disappeared still alive and took lots of my memory. The problem is when my list has many items. App will crash because the memory is not enough. 
=> I tried to change to Gridview.builder. The problem is solved. Gridview.builder release old item which disappeared and rebuild when items are showed on screen.

**Comment by rmControls** [comment]
seems like this PR [#188](https://github.com/letsar/flutter_staggered_grid_view/pull/188) improve the performance....

I just tested with my case and looks better...

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by PhantomRay** [comment]
Maybe related to #113

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
