### ISSUE TITLE
Padding to bottom to avoid bottomBar?

### ISSUE THREAD

**Issue by jinfagang** [letsar/flutter_staggered_grid_view#181]
![image](https://user-images.githubusercontent.com/21303438/120074238-80b3e000-c0ce-11eb-90a8-6b1b2029a96b.png)

![image](https://user-images.githubusercontent.com/21303438/120074250-90332900-c0ce-11eb-9c46-141affbfe6f9.png)

For staggeredGridView, it can not **place lastest item above bottomBar** while **listview can handle it**.

What I mean is that I want the list scroll behind the bottomBar, so it must extend to the whole screen. If staggeredGridView do so, the last item will behind bottomBar, but not listview.

You can try it with blurred bottomBar or translucent, you will notice it.

**Comment by jinfagang** [comment]
But I can not simply set a padding.

**Comment by clragon** [comment]
The grid view contructors have a `EdgeInsetsGeometry? padding,` parameter.
Does this not suffice your needs?

You can add a padding at the bottom like this

```dart
StaggeredGridView(
    padgging: EdgeInsets.only(bottom: 24),
)
```

**Comment by jinfagang** [comment]
@clragon I tried this, after set padding, the whole StaggeredGridView will above bottombar. As you can see, my bottombar actually is a curve which you can see things behind the bar. 

I want it behind the bar, but also, when it scrolled to the last item, it will jump up and not blinded by bottombar.

Does myself clear about my issue? Clearly padding doesn't fits my demands.

This behavious supported by Listview though.
