### ISSUE TITLE
Tile overlap using StaggeredTile.fit

### ISSUE THREAD

**Issue by martesabt** [letsar/flutter_staggered_grid_view#182]
Hi!

When I use **StaggeredTile.fit** with **Image.network**, the items with StaggeredTile.fit overlap the below list items, as you can see in the first attached image.

But if the state changes (click on the screen, scroll the list, force it programmatically) then the overlap fixes. As you can see in the second attached image.

This is my **staggeredTileBuilder**:

```
staggeredTileBuilder: (int index) {
  // We detect if the item is an Advert
  if (_items[index] is Advert) {
    // If the Advert item has to fit 2 columns
    if (_items[index].columnValue == 2) {
      // This is the Advert item that overlaps the product items
      return new StaggeredTile.fit(2);
    }

    // The other Adverts has specific column/row fit
    return new StaggeredTile.count(
      _items[index].columnValue,
      _items[index].row,
    );

  } else {
    // All Product items has same size
    return new StaggeredTile.count(1, 1.5);
   }
}
```

Does anyone experienced this?

Thanks!

<img width="431" alt="overlap_1" src="https://user-images.githubusercontent.com/47976038/120459812-d3c0b800-c398-11eb-8e9c-aa92ba28a259.png">

<img width="432" alt="overlap_2" src="https://user-images.githubusercontent.com/47976038/120459900-e89d4b80-c398-11eb-9e2c-defd4a926598.png">

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
