### ISSUE TITLE
Clipping with SliverStaggeredGrid

### ISSUE THREAD

**Issue by salahkamal** [letsar/flutter_staggered_grid_view#183]
Can I apply ClippRRect to Sliver widget?

**Comment by girish54321** [comment]
Yes you can!

**Comment by salahkamal** [comment]
How please ..? ClipRRect not a sliver widget .

**Comment by girish54321** [comment]
What are you trying to do any shape or just border borderRadius?

**Comment by salahkamal** [comment]
Yes just border redius like border redius from ClipRRect

**Comment by salahkamal** [comment]
Any updates ??!

**Comment by girish54321** [comment]
Try this
[Link](https://github.com/girish54321/Chitr/blob/master/lib/widget/appNetWorkImage.dart)
