### ISSUE TITLE
How to jump to item index?

### ISSUE THREAD

**Issue by sinhpn92** [letsar/flutter_staggered_grid_view#184]
I am looking for a solution to implement a scrollable tab view that's can be selected by scroll the list.
My grid items have the section separated by item type. I saw this lib `https://github.com/google/flutter.widgets/tree/master/packages/scrollable_positioned_list`

But It's still not support for `flutter_staggered_grid_view`. 
How can I implement a scrollable list like that? Have any suggest to do it?

Thank you so much

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
