### ISSUE TITLE
Give the ability to change ClipBehavior 

### ISSUE THREAD

**Issue by AndyDavidJoyce** [letsar/flutter_staggered_grid_view#186]
It seems like by default the StaggeredGridViews ClipBehavior is set to Clip.hardEdge and there is no way to change it.

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview with a CustomScrollView and SliverMasonryGrid? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.

**Comment by CheyenneForbes** [comment]
Are there any plans to implement this feature? Being able to control clipBehavior will be beneficial in cases where we'd like to have the space between cells but also want to have widgets being able to appear over the space beside their parent cells.

**Comment by CheyenneForbes** [comment]
For future reference, anyone looking to achieve the same can use a [FractionalTranslation](https://api.flutter.dev/flutter/widgets/FractionalTranslation-class.html) for their grid item. Events will be a little complex so also take advantage of the [HitTestBehavior](https://api.flutter.dev/flutter/rendering/HitTestBehavior.html) property on your grid and grid items' GestureDetector, etc.
