### ISSUE TITLE
Changing `crossAxisCount` programmatically doesn't rearrange items in one row

### ISSUE THREAD

**Issue by JonasHiltl** [letsar/flutter_staggered_grid_view#194]
I want to give the ability to rearrange the items through a `CupertinoSlidingSegmentedControl`. The Slider can have a value of 1, 2 or 3. These numbers should reflect the numbers of items in one Row. 
When changing the `segmentedControlGroupValue` and as a result the `crossAxisCount` the items size changes but they don't get rearranged and positioned in the same Row. Only when I restart the app and set the `crossAxisCount` to 2 the grid gets arranged with two items in one row but it is not possible to programmatically change this value while running the app. Or did I just implement it wrong?

```dart
SliverStaggeredGrid.countBuilder(
  mainAxisSpacing: kSmallPadding,
  crossAxisCount: segmentedControlGroupValue ?? 1,
  itemCount: 6,
  staggeredTileBuilder: (int index) => StaggeredTile.fit(1),
  itemBuilder: (BuildContext context, int i) => Card(
    child: Container(
      color: Colors.green,
      padding: EdgeInsets.all(kMediumPadding),
      child: Text(
        i.toString(),
      ),
    ),
  ),
),
```
```dart
CupertinoSlidingSegmentedControl(
  groupValue: segmentedControlGroupValue,
  padding: const EdgeInsets.all(6),
  children: const {
    1: Icon(Icons.menu),
    2: Icon(
      QuaderFont.th_large_1,
      size: 16,
    ),
    3: Icon(Icons.apps)
  },
  onValueChanged: (value) => setState(() {
    segmentedControlGroupValue = value as int?;
  }),
),
```

![Unbenannt1](https://user-images.githubusercontent.com/71456708/126909433-f0d79878-8ad5-4a4a-9807-6b952884e4a5.JPG)
![Unbenannt2](https://user-images.githubusercontent.com/71456708/126909435-0546e527-11a8-4c4c-9aa8-2d0b48d21900.JPG)
![Unbenannt3](https://user-images.githubusercontent.com/71456708/126909436-48432e33-bea1-4850-bf33-086782758c1d.JPG)

**Comment by babaosoftware** [comment]
I have the same issue, which is a deal breaker for me. Also, when rotating the phone, the grid is extremely slow to redraw. I tried to use it with a large number of items, over 1000, and it's just unusable after rotation. I have absolutely no problems like that with GridView.builder, which I'm using currently, except that I'm stuck with the same size tiles.

**Comment by babaosoftware** [comment]
@JonasHiltl If your tiles are all the same size, try GridView.builder with SliverGridDelegateWithFixedCrossAxisCount. It's fast and you can programmatically change cross axis count without problems.

**Comment by JonasHiltl** [comment]
@babaosoftware Thanks for your repy, I already did it with `GridView.builder`. I hoped that staggered GridView would give me a more dynamic way without having to define a static size of the tiles but that didn't work out for me.

**Comment by gaohanas** [comment]
我也有同样的问题，当我改变crossAxisCount的值希望动态改变列数，但是没有什么作用

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by omar-bizreh** [comment]
> Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

It fixes this issue for me, now when window resizes on Linux the widget reflects new value for crossAxisCount

**Comment by letsar** [comment]
Closing since it's resolved
