### ISSUE TITLE
staggeredTiles

### ISSUE THREAD

**Issue by PhoenixLeeSin** [letsar/flutter_staggered_grid_view#195]
How should I understand the concept of StaggeredTile? What is the relationship between crossAxisCount and staggeredTiles?
in home.dart in demo, line 70, set 
`
crossAxisCount: 4,
`
it do not be 4 column.
 i can't understand the  description of read.me about staggeredTiles

**Comment by maares** [comment]
Hi @PhoenixLeeSin, please bear in mind this space is intended for reporting bugs or propose improvements. Try searching in tech program forums. Non the less there's a quick video explaining how to use this package.

https://www.youtube.com/watch?v=XNwL_9ur8R8

**Comment by PhoenixLeeSin** [comment]
@maares  ok  whatever, ths,

**Comment by PhoenixLeeSin** [comment]
> Hi @PhoenixLeeSin, please bear in mind this space is intended for reporting bugs or propose improvements. Try searching in tech program forums. Non the less there's a quick video explaining how to use this package.
> 
> https://www.youtube.com/watch?v=XNwL_9ur8R8

ths very much, watch this video, i can understand this.
