### ISSUE TITLE
Screenshot links on pub seems to be broken

### ISSUE THREAD

**Issue by asaarnak** [letsar/flutter_staggered_grid_view#2]
Propably because of relative url. Works fine on github!
https://pub.dartlang.org/packages/flutter_staggered_grid_view

**Comment by letsar** [comment]
That's strange I used absolute urls.

**Comment by letsar** [comment]
Ok I found, I used a bad url. I should have used something like https://raw.githubusercontent.com/letsar/flutter_staggered_grid_view/master/doc/images/example_01.PNG
