### ISSUE TITLE
Add support for pagination

### ISSUE THREAD

**Issue by anderscheow** [letsar/flutter_staggered_grid_view#20]
The library itself is wonderful. But I would suggest to add support for Pagination. It would be great if this library able to integrate with this pagination library [flutter_pagewise](https://github.com/AbdulRahmanAlHamali/flutter_pagewise)

**Comment by tapkain** [comment]
That would be awesome

**Comment by jamesblasco** [comment]
I think it would make more sense if the package flutter_pagewise implements their solution also with the `StaggeredGridView`, the same they implemented it for ListView or GridView. It will be easier to maintain there.

Implementing pagination without that package could be a good option too

**Comment by letsar** [comment]
Pagination is not in the scope of the library. It can be achieved like with a ListView or GridView.
