### ISSUE TITLE
Is it possible to scroll to a specific index?

### ISSUE THREAD

**Issue by heyarny** [letsar/flutter_staggered_grid_view#200]
Is there a way to scroll to a specific index?

**Comment by PaulLVoelker** [comment]
If you know the height of each element you can write a counting system and then you can use `scrollController.jumpTo(double height)` to jump to the index accordingly. If you don't know the height of the elements you could build a measuring function / layout finder for them.

**Comment by letsar** [comment]
Hi, this feature won't be added in this package but maybe you can use this one (https://pub.dev/packages/scroll_to_index) to achieve the desired effect.
