### ISSUE TITLE
Constant errors:  Unhandled Exception: type 'SliverHitTestResult' is not a subtype of type 'BoxHitTestResult'

### ISSUE THREAD

**Issue by amigax** [letsar/flutter_staggered_grid_view#202]

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
