### ISSUE TITLE
Item scrolls through the StaggeredGridView bottom limit

### ISSUE THREAD

**Issue by Alcachofraz** [letsar/flutter_staggered_grid_view#206]
In the video attached you can see the list elements scroll through the limits of the StaggeredGridView.
My StaggeredGridView is inside a Expanded widget (with a specified flex) which is inside a Column.

Any ideas why this could be happening?

https://user-images.githubusercontent.com/75852333/139671983-19999ce8-1b75-4bb2-b4b4-8cafbee60ac1.mp4

**Comment by mabroukb** [comment]
Hi,
We had the same issue. We figured out that crossAxisCount option and StaggeredTile. Fit() must be correlated.

When we set crossAxisCount to be double of  StaggeredTile. Fit(), the issue resolved.

We cannot explain it.

Can you try on you side and may be try to explain it with us ?

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
