### ISSUE TITLE
StaggeredGridView item count A small number shows abnormality. itemCount 数量少显示异常。

### ISSUE THREAD

**Issue by hanleiZoro** [letsar/flutter_staggered_grid_view#211]
item count： 2 ｜ 3 ｜ 4
The test result is that if the rendered content cannot fill the screen, an error will be reported. In my project, the screen cannot be filled with a small amount, and then an error will be displayed, but at the level of my use, I cannot handle this error.
Unhandled Exception: Null check operator used on a null value.
<img width="968" alt="image" src="https://user-images.githubusercontent.com/38712031/144548154-2457f53a-6bf9-48fc-8381-6a97e95a7c7a.png">
数量过少就无法显示。 还请帮忙处理下。

**Comment by hanleiZoro** [comment]
测试结果是 渲染内容无法填满屏幕就会报错，在我的项目里数量少的情况下无法填满屏幕，然后会提示错误，但是在我使用层面我无法处理这个错误

**Comment by letsar** [comment]
English please.
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
