### ISSUE TITLE
Jump to index in MasonryGridView

### ISSUE THREAD

**Issue by muhammadalkady** [letsar/flutter_staggered_grid_view#213]
How to jump to an index in `MasonryGridView`?
I have a `MasonryGridView` and a list of alphabets .. the click-on alphabet should jump to the first item with the clicked letter?

![Screenshot 2021-12-13 115855](https://user-images.githubusercontent.com/44714079/145793651-1554f7ad-ac5a-4347-b4d5-af154bf2bf01.png)

```
MasonryGridView.extent(
          padding: const EdgeInsets.only(right: 8, left: 8),
          controller: _gridScrollController,
          maxCrossAxisExtent: 450,
          itemCount: uiReciters.length,
          itemBuilder: (BuildContext context, int index) {
            final reciter = uiReciters[index];
            return Card(
              color: Theme.of(context).colorScheme.primaryVariant,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Padding(
                    padding: const EdgeInsets.only(
                      right: 16.0,
                      left: 16.0,
                      top: 4,
                      bottom: 4,
                    ),
                    child: Text(
                      reciter.name,
                      textAlign: TextAlign.start,
                      style: const TextStyle(fontSize: 20),
                    ),
                  ),
                  const Divider(
                    thickness: 2,
                    height: 2,
                  ),
                  Column(
                    children: List.generate(
                      reciter.uiRewayas.length,
                      (index) => Padding(
                        padding: const EdgeInsets.only(left: 8.0, right: 8.0),
                        child: Text("Rewaya ${index + 1}"),
                      ),
                    ),
                  )
                ],
              ),
            );
          },
        )
```

**Comment by letsar** [comment]
Hi, this feature won't be added in this package but maybe you can use this one (https://pub.dev/packages/scroll_to_index) to achieve the desired effect.

**Comment by muhammadalkady** [comment]
Hi,
Thanks for this great package.
`scroll_to_index` package does not support jump.
I have written a function to calculate offset as item height is known 

`Future<double> calculateOffsets(int index, List<UIReciter> items) async {
    //TODO dynamic column count.
    const columnsCount = 2;
    final columnsLastOffset = List.generate(columnsCount, (index) => 0.0);
    for (int i = 0; i < items.length; i++) {
      final minC = columnsLastOffset.reduce(min);
      final minCIndex = columnsLastOffset.indexOf(minC);
      if (index == i) {
        return columnsLastOffset[minCIndex];
      }
      columnsLastOffset[minCIndex] += getItemHeight(items[i]);
    }
    return 0.0;
  }
`

**Comment by letsar** [comment]
scroll_to_index supports jumps, or I didn't understand your question:
`controller.scrollToIndex(index, preferPosition: AutoScrollPosition.begin)`

**Comment by muhammadalkady** [comment]
I does not support jump.
https://github.com/quire-io/scroll-to-index/issues/53

**Comment by letsar** [comment]
Oh ok, I misunderstood. I thought you to scroll to a specific position.
This feature won't be added either, as I think we would need a more generic solution.
