### ISSUE TITLE
Remove extra space on fixed quitled grid

### ISSUE THREAD

**Issue by Pierre-Monier** [letsar/flutter_staggered_grid_view#216]
I want to remove extra space at the end of a fixed quitled grid. 

I needed this feature for one of the app I'm working on, I don't know if there is already away of doing this ?

For example when you have a `childCount` to 20 it look like this :

![false](https://user-images.githubusercontent.com/65488471/147466372-dc39106b-2140-4e3c-ba95-0ea76dcfeeee.gif)

- I would like to make it look like this

![true](https://user-images.githubusercontent.com/65488471/147466427-3ac79277-6606-4849-bb68-e7d9f74a4821.gif)

I'm working on it but if this is already a solved problem I would be happy to know how to do it :)

**Comment by letsar** [comment]
Didn't saw that issue, I will also look at it. Thank you for raising this 👍

**Comment by letsar** [comment]
I fixed it in 0.5.0-dev.5, thanks again for raising this issue.
