### ISSUE TITLE
I don't know use it with dynamic items (adding and removing)

### ISSUE THREAD

**Issue by Himhotep** [letsar/flutter_staggered_grid_view#22]
Your package is great but I don't know use it with dynamic items because setstate() doesn't call to the build method of every item (I think). The same code with a GridView.builder works fine.

I attach code removing and adding items and a video.

class _MyHomePageState extends State<MyHomePage> {
  final _scaffoldkey = new GlobalKey<ScaffoldState>();
  final _streamController = StreamController<Item>();
  List<Item> _items = [];
  int _counter = 0;

  _itemGet(int index) {
    return _items[index];
  }

  _itemChanged(Item item) {
    var i = _items?.firstWhere((t) => t.id == item.id);
    if (i != null) {
      _scaffoldkey.currentState.showSnackBar(new SnackBar(content: new Text("Deleted ${i.id}?")));
      setState(() {
        _items.remove(i);
      });
    }
  }

  _itemAdd() {
    setState(() {
      _items.add(Item(_counter++, _streamController));
    });
  }

  @override
  void initState() {
    super.initState();
    _streamController.stream.listen((item) => _itemChanged(item));
    for (var i = 0; i < 4; i++)
      _items.add(Item(_counter++, _streamController));
  }

  @override
  void dispose() {
    _streamController.close();
    super.dispose();
  }

  _staggeredGridView() {
    return StaggeredGridView.countBuilder(
      crossAxisCount: 4,
      mainAxisSpacing: 0.0,
      crossAxisSpacing: 8.0,
      padding: EdgeInsets.all(8.0),
      itemCount: _items.length,
      itemBuilder: (BuildContext context, int index) => _itemGet(index),
      staggeredTileBuilder: (int index) => StaggeredTile.fit(1),
    );
  }

  _gridView() {
    return GridView.builder(
      padding: EdgeInsets.all(4.0),
      itemCount: _items.length,
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
        childAspectRatio: 4.0,
        crossAxisSpacing: 4.0,
        crossAxisCount: 4,
        mainAxisSpacing: 4.0,
      ),
      itemBuilder: (BuildContext context, int index) => _itemGet(index),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      key: _scaffoldkey,
      appBar: AppBar(title: Text(widget.title)),
      body: _staggeredGridView(),
//      body: _gridView(),
      floatingActionButton: FloatingActionButton(onPressed: _itemAdd, child: Icon(Icons.add)),
    );
  }
}

class Item extends StatelessWidget {
  final int id;
  final StreamController<Item> streamController;

  Item(this.id, this.streamController);

  _remove() {
    streamController.add(this);
  }

  @override
  Widget build(BuildContext context) {
    return RaisedButton.icon(onPressed: _remove, icon: Icon(Icons.delete), label: Text('$id'));
  }
}

![untitled](https://user-images.githubusercontent.com/24211508/50514703-429ad800-0aa0-11e9-9d6f-cd9fa6e0d9df.gif)

**Comment by pj0579** [comment]
change data List length will useful

**Comment by letsar** [comment]
Hi, I think this is related to the #23 which I think I fixed it.
Can you check with the master branch?

**Comment by letsar** [comment]
Great :-). I published the fix in version 0.2.6.
