### ISSUE TITLE
how i can use this plugin in CustomScrollView

### ISSUE THREAD

**Issue by shichunlei** [letsar/flutter_staggered_grid_view#220]
flutter_staggered_grid_view: ^0.6.0

**Comment by letsar** [comment]
Can you provide more details on what you want to do? The answer is also maybe in the [wiki](https://github.com/letsar/flutter_staggered_grid_view/wiki).

**Comment by shichunlei** [comment]
![矩形](https://user-images.githubusercontent.com/7146745/147897518-ce412a09-2630-4d57-b846-d978b00233c4.jpg)

Now I can only put MasonryGridView in SliverToBoxAdapter and use it, I want to know how this plug-in can be used directly in CustomScrollView

my code:

`CustomScrollView(slivers: [
          SliverAppBar(
            /* more code */
          ),
          SliverToBoxAdapter(child: Container(height: 100, color: Colors.red)),
          SliverToBoxAdapter(
              child: MasonryGridView.custom(
                  shrinkWrap: true,
                  physics: NeverScrollableScrollPhysics(),
                  mainAxisSpacing: 5,
                  crossAxisSpacing: 5,
                  childrenDelegate: SliverChildBuilderDelegate((_, index) {
                    return Container();
                  }, childCount: 10),
                  gridDelegate: SliverSimpleGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2)))
        ])`

**Comment by letsar** [comment]
The answer is on this [page](https://github.com/letsar/flutter_staggered_grid_view/wiki/Masonry) of the wiki

**Comment by Benjf29** [comment]
> The answer is on this [page](https://github.com/letsar/flutter_staggered_grid_view/wiki/Masonry) of the wiki

Thank, that's the perfect response 👍
