### ISSUE TITLE
Span column

### ISSUE THREAD

**Issue by xxJeevesxx** [letsar/flutter_staggered_grid_view#224]
Since the rewrite, I've been looking through the docs and I can't quite figure out how to accomplish this. Maybe it's not possible or I just don't understand enough. I see the other issue (#223) about `StaggeredGridView.countBuilder` (which is what I used before) not existing anymore and your comment about using the `MasonryGrid` but I can't figure it out. I'm wanting to accomplish something like this, where the first element is spanned across both columns and the rest are in grid fashion.  I've accomplish the layout with the `StaggeredGrid` but as explained in the docs it's not scrollable and all the elements are drawn even if not visible. Wondering if there is a way to accomplish this. Thanks for your time!

![image](https://user-images.githubusercontent.com/3445444/148306202-2d3280f0-3fbd-4dbb-9158-68e4c9041046.png)

**Comment by letsar** [comment]
For the use case you described, I wouldn't use this package. Everything is available directly in Flutter through the `CustomScrollView`.
I would put a `SliverToBoxAdapter` as the first sliver (which would take the available width) and a `SliverGrid` as the second sliver.

**Comment by xxJeevesxx** [comment]
Ah, I see, ok. I appreciate the response and the feedback. Thank you so much!

**Comment by NaikSoftware** [comment]
Reason why we use this package is ~staggered grid~
Without this feature package not needed. Thanks for "rewriting", but only old version still usable.

**Comment by xxJeevesxx** [comment]
> Reason why we use this package is *staggered grid*
> 
> Without this feature package not needed. Thanks for "rewriting", but only old version is usable. 

I think that's a little harsh. I did what @letsar suggested and everything is working beautifully. This package seems to be for more custom and unique type grid displays (as described in the examples). My issue was/is inexperience with flutter and what's available and how to implement.

**Comment by xxJeevesxx** [comment]
That's true. But depending on your use case it's probably accomplished achievable in vanilla flutter without a package, just as mine was. I don't know much but could try to help if you describe your use case.

**Comment by NaikSoftware** [comment]
@xxJeevesxx my case - items with headers. Yes, I know, that is achievable with slivers - grid view for every block of items, but without lazy rendering. Whole block will be rendered at once.
![Screenshot_20220111-101756](https://user-images.githubusercontent.com/4218994/148905896-1472b71f-07b9-4e23-8969-69af9950482f.png)

**Comment by ll** [comment]
That would be greate if MasonryGridView support params like "header"，Otherwise the Header will cover the MasonryGridView when scrolling.
