### ISSUE TITLE
Undefined name 'StaggeredGridView

### ISSUE THREAD

**Issue by kevin4dhd** [letsar/flutter_staggered_grid_view#227]
Undefined name 'StaggeredGridView'.
Try correcting the name to one that is defined, or defining the name.

StaggeredGridView no longer exists, what to use now?

**Comment by khumam** [comment]
Me too. I think it's removed from the library.
You can try `StaggeredGrid.count` instead

**Comment by thanhnh98** [comment]
and how to implement scrollController on StaggeredGrid.count ? 

> Me too. I think it's removed from the library. You can try `StaggeredGrid.count` instead

**Comment by khumam** [comment]
> and how to implement scrollController on StaggeredGrid.count ?
> 
> > Me too. I think it's removed from the library. You can try `StaggeredGrid.count` instead

Are you  mean the scroll widget? I haven't find the solution yet. I still use the GridView in scrolling widget

**Comment by ValentinVignal** [comment]
Here is how I changed my code:

Previously

```dart
StaggeredGridView(
  scrollController: scrollController,
),
```

Now

```dart
SingleChildScrollView(
  scrollController: scrollController,
  child: StaggeredGrid.count(),
),
```

**Comment by peksel** [comment]
https://github.com/letsar/flutter_staggered_grid_view/issues/226#issuecomment-1126771747

**Comment by letsar** [comment]
There is a wiki to help you choose the right API for your needs: https://github.com/letsar/flutter_staggered_grid_view/wiki

**Comment by ahmadhassan136** [comment]
I have mentioned the answer in there [https://github.com/letsar/flutter_staggered_grid_view/issues/226#issuecomment-1260391189](url)
