### ISSUE TITLE
Does this  package not implement lazy loading?

### ISSUE THREAD

**Issue by Junesui** [letsar/flutter_staggered_grid_view#228]
Please let me know if there is a solution. thanks!!

**Comment by letsar** [comment]
Lazy loading is not the purpose of this package. You can do it with a ScrollController the same way you can do it in a ListView.

**Comment by TheCarpetMerchant** [comment]
Hello,
I think that by "lazy loading", the user meant building the widget only when it comes into view. This is something I am interested in as well. I'm using StaggeredGrid and it works beautifully but all widgets are built as soon as the list is, which is a problem performance-wise.
