### ISSUE TITLE
Scroll Index Limit for Quilted Layout

### ISSUE THREAD

**Issue by CalvinTp** [letsar/flutter_staggered_grid_view#229]
I am currently migrating from StaggeredGridView.countBuilder to Quilted Layout based on the latest version. Based the readme and examples from the codes, I am able to re-create my current UI arrangement (from StaggeredGridView.countBuilder to SliverQuiltedGridDelegate Layout); but unable to find information on how to specify the limit of the scroll index. Currently the layout will continue to scroll and generate empty layout (since the Grid pattern are repeated). 

Based on the example provided from this library, where can I specify the scroll index limit? 

```
GridView.custom(
        gridDelegate: SliverQuiltedGridDelegate(
          crossAxisCount: 4,
          mainAxisSpacing: 4,
          crossAxisSpacing: 4,
          repeatPattern: QuiltedGridRepeatPattern.inverted,
          pattern: pattern,
        ),
        childrenDelegate: SliverChildBuilderDelegate(
          (context, index) {
            final tile = pattern[index % pattern.length];
            return ImageTile(
              index: index,
              width: tile.crossAxisCount * 100,
              height: tile.mainAxisCount * 100,
            );
          },
        ),
```

**Comment by teganscott** [comment]
@CalvinTp did you ever figure out how to limit the number of children?

**Comment by teganscott** [comment]
If anyone else ends up here you can return null when index surpasses list length. 

`childrenDelegate: SliverChildBuilderDelegate((context, index) {
          if (index >= list.length) {
            return null;
          }
          return Tile();`

**Comment by letsar** [comment]
Closing since https://github.com/letsar/flutter_staggered_grid_view/issues/229#issuecomment-1122894214 is the solution
