### ISSUE TITLE
Wrong division getMinChildIndexForScrollOffset

### ISSUE THREAD

**Issue by NktnSmn** [letsar/flutter_staggered_grid_view#232]
Hello! 
I have found a problem. You may catch it if you use SliverQuiltedGridDelegate's crossAxisCount with value 2 and one QuiltedGridTile(2, 2). 
The reason is in wrong division - [getMinChildIndexForScrollOffset](https://github.com/letsar/flutter_staggered_grid_view/blob/a1f0b9b1d7426fd1060a938885f0129a5faf705e/lib/src/layouts/quilted.dart#L236). It may be fixed with division by pattern.mainAxisCellCount like in getMaxChildIndexForScrollOffset. Please correct me if I’m wrong.

https://user-images.githubusercontent.com/97748438/152995037-dbdffae8-a4ce-45f0-bcb7-0cfe8f629eb8.mp4

**Comment by letsar** [comment]
Yes, I think you're right, I'll fix that, thanks a lot!

**Comment by letsar** [comment]
Fixed in 0.6.2. Thanks again for your help.
