### ISSUE TITLE
[Help Request] I want to achieve custom Grid pattern 

### ISSUE THREAD

**Issue by arslankaleem7229** [letsar/flutter_staggered_grid_view#236]
I am working on this for a while but didn't find how to achieve my desired design which is just random tiles with a fixed pattern that some times it comes two tiles in column sometimes it would be a big block ... Here is what I want
Thanks in advance 

<img width="427" alt="Screenshot 2022-02-28 at 7 30 15 PM" src="https://user-images.githubusercontent.com/49631685/156000406-c651aec9-8864-4a94-921c-89a6098fba8a.png">

**Comment by letsar** [comment]
You can use the [Quilted](https://github.com/letsar/flutter_staggered_grid_view/wiki/Quilted) layout for this kind of pattern.
Something like this, may be what you want:
```dart
SliverQuiltedGridDelegate(
  crossAxisCount: 2,
  mainAxisSpacing: 4,
  crossAxisSpacing: 4,
  repeatPattern: QuiltedGridRepeatPattern.inverted,
  pattern: const [
    QuiltedGridTile(1, 1),
    QuiltedGridTile(1, 1),
    QuiltedGridTile(2, 2),
    QuiltedGridTile(1, 1),
    QuiltedGridTile(1, 1),
  ],
),
```

**Comment by letsar** [comment]
Closing since no response since a while.
