### ISSUE TITLE
SliverMasonryGrid - scroll offset not being restored correctly

### ISSUE THREAD

**Issue by enhancient** [letsar/flutter_staggered_grid_view#241]
Firstly, thank you for this fantastic project.

After upgrading (0.6.1) to SliverMasonryGrid from the old SliverStaggeredGridView, I'm finding that the scroll position is not restored correctly when I switch tabs in my app (it scrolls to somewhere near the top). This is despite there being a PageStorageKey set on the CustomScrollView I'm using. If I swap to SliverAlignedGrid or the built in SliverGrid, it restores the position correctly, so it seems to be specifically related to SliverMasonryGrid.

Can you kindly look into this?

**Comment by letsar** [comment]
Can you provide a code sample I could just copy/paste and run?

**Comment by letsar** [comment]
Closing since no response since a while.
