### ISSUE TITLE
Undefined name 'StaggeredGridView'. after upgrading to 0.6.1

### ISSUE THREAD

**Issue by RoyalCoder88** [letsar/flutter_staggered_grid_view#242]
Hi friends,

After upgrading to version 0.6.1 I get this error on the:
`Undefined name 'StaggeredGridView'.
Try correcting the name to one that is defined, or defining the name.dart[undefined_identifier](https://dart.dev/diagnostics/undefined_identifier)`

in:

`            child: snapshot.data!.docs.isNotEmpty
                ? StaggeredGridView.countBuilder(
                    crossAxisCount: 3,
                    staggeredTileBuilder: (index) => StaggeredTile.count(
                        (index % 6 == 0) ? 2 : 1, (index % 6 == 0) ? 2 : 1),
                    mainAxisSpacing: 2,
                    crossAxisSpacing: 2,
                    itemCount: snapshot.data!.docs.length,
                    itemBuilder: (context, int index) {
                      List stories = snapshot.data!.docs;
                      return buildItem(stories, index);
                    },
                  )`
Please guide me to fix these errors, thank in advance!
![Screenshot 2022-03-29 114252](https://user-images.githubusercontent.com/6507433/160601056-15dba1af-b706-44bb-ae67-2183b61ed9ba.png)

**Comment by Farrukh1198** [comment]
I also get that error

**Comment by Tony0205** [comment]
me too.. I have a similar problem :(
![스크린샷 2022-04-07 오후 4 30 05](https://user-images.githubusercontent.com/27188150/162144447-194a8650-0420-44e6-9aeb-7ea624bc0604.png)

**Comment by SahibG** [comment]
Same here, any updates?

**Comment by Farrukh1198** [comment]
I've used version 0.4.0. It has null safety and and it has everything we need

**Comment by Panossa** [comment]
Same problem here. Ended up downgrading to 0.4.0, too. Why even bother updating this package if such a basic feature is lost? The new staggered variants of 0.6.X all expect a full children[] array which is rarely useful.

**Comment by letsar** [comment]
The lib has been refactored, StaggeredGridView does not exist anymore, please refer to the wiki.

**Comment by MarceloRab** [comment]
Same problem here
