### ISSUE TITLE
RangeError (index): Invalid value: Not in inclusive range SliverMasonryGrid.count

### ISSUE THREAD

**Issue by mattg1995** [letsar/flutter_staggered_grid_view#243]
Hi, 

Previously I had this code before upgrading to 0.6.0

```
SliverStaggeredGrid.count(
                              crossAxisCount: columnsLength,
                              children: List.generate(
                                feeds.length,
                                (int index) {
                                  return _Tile(
                                    feeds[index],
                                    plus,
                                  );
                                },
                              ),
                              staggeredTiles: List.generate(
                                feeds.length,
                                (int index) {
                                  return const StaggeredTile.fit(1);
                                },
                              ),
                            )
```

I have now upgraded to this 

```
                            SliverMasonryGrid.count(
                              crossAxisCount: columnsLength,
                              itemBuilder: (context, index) {
                                return _Tile(
                                  feeds[index],
                                  plus,
                                );
                              },
                            ),
```

My list is populated from API calls which updates as the user scrolls but I am getting the error RangeError (index): Invalid value: Not in inclusive range as soon as it tries to show data outside of the initial list

Please can someone give me guidance on this?

**Comment by MCode-Team** [comment]
Big Mistake never use shrinkWrap(when you have alot of items) in your list(performance issues).

2022 Update version flutter staggered has updated itself and removed SliverStaggeredGrid in the new version, you can use QuiltedGridDelegate. like this:
      
      CustomScrollView(
      slivers: [
        SliverGrid(
            delegate: SliverChildBuilderDelegate(
              (context, index) => Container(
                color: Colors.cyanAccent,
                child: Text("$index"),
              ),
              childCount: 44,
            ),
            gridDelegate: SliverQuiltedGridDelegate(
              crossAxisCount: 3,
              mainAxisSpacing: 4,
              crossAxisSpacing: 4,
              repeatPattern: QuiltedGridRepeatPattern.inverted,
              pattern: const [
                QuiltedGridTile(2, 1),
                QuiltedGridTile(2, 2),
                QuiltedGridTile(1, 1),
                QuiltedGridTile(1, 1),
                QuiltedGridTile(1, 1),
              ],
            ))
      ],
    ),
    
    Cr.
    https://stackoverflow.com/questions/70549115/how-to-implement-staggered-grid-view-with-slivers-in-flutter
