### ISSUE TITLE
Reorderable GridView

### ISSUE THREAD

**Issue by jargalbat** [letsar/flutter_staggered_grid_view#245]
Please add the drag and reorder feature. 
Thank you.

**Comment by qq1023308356** [comment]
https://pub.flutter-io.cn/packages/drag_anim  can use this

**Comment by qq1023308356** [comment]
> 请添加拖动和重新排序功能。 谢谢你。

https://pub.flutter-io.cn/packages/drag_anim  can use this

**Comment by qq1023308356** [comment]
> Please add the drag and reorder feature. Thank you.

https://pub.flutter-io.cn/packages/drag_anim can use this

**Comment by letsar** [comment]
duplicates #3 #80

**Comment by LiJinJinJIn** [comment]
> > 请添加拖动和重新排序功能。谢谢。
> 
> https://pub.flutter-io.cn/packages/drag_anim可以用这个

谢谢，我正好需要，不过不知道有没有自动补足的那种，
就类似于iphone手机那样，小组件会填充到空余的地方

**Comment by LiJinJinJIn** [comment]
> > 请添加拖动和重新排序功能。谢谢。
> 
> https://pub.flutter-io.cn/packages/drag_anim可以用这个

似乎这个项目并没有完整的案例

**Comment by qq1023308356** [comment]
> > > 请添加拖动和重新排序功能。谢谢。
> > 
> > 
> > [https://pub.flutter-io.cn/packages/drag_anim 可以用这个](https://pub.flutter-io.cn/packages/drag_anim%E5%8F%AF%E4%BB%A5%E7%94%A8%E8%BF%99%E4%B8%AA)
> 
> 似乎这个项目并没有完整的案例

看你用的布局，你使用的支持自动补齐就支持，现在已经添加了，你可以看看
