### ISSUE TITLE
How to implement the staggeredTitleBuilder?

### ISSUE THREAD

**Issue by minhnguyenandpad** [letsar/flutter_staggered_grid_view#246]
In the old version it have everything we need like the staggeredTitleBuilder so we could create what ever shapes of the gridview we want. Now you seperate them with no clear document. Why are you trying to ruin a good package?

**Comment by peksel** [comment]
Use version below, it has everything you need with null safety

flutter_staggered_grid_view: ^0.4.0

**Comment by mattg1995** [comment]
> Use version below, it has everything you need with null safety
> 
> flutter_staggered_grid_view: ^0.4.0

This version has performance issues, especially with sliver masonry grid. memory excess is very common.

**Comment by letsar** [comment]
> Why are you trying to ruin a good package?

Thanks for the comment, why are you trying to ruin my mood? Why do you think I would want to help when I read this?

**Comment by letsar** [comment]
Closing since no response since a while.
