### ISSUE TITLE
items disappear when scrolling

### ISSUE THREAD

**Issue by h1amza** [letsar/flutter_staggered_grid_view#248]
///code:

GridView.builder(
      padding: EdgeInsets.zero,
      gridDelegate: SliverQuiltedGridDelegate(
        crossAxisCount: 8,
        pattern: const <QuiltedGridTile>[
          QuiltedGridTile(4, 4), // 0  left
          QuiltedGridTile(6, 4), // 1  right
          QuiltedGridTile(5, 4), // 2  left
          QuiltedGridTile(4, 4), // 3  right
          QuiltedGridTile(4, 4), // 4  left
          QuiltedGridTile(3, 4), // 5  right
        ],
      ),
      itemBuilder: (BuildContext context, int index) =>
          Tile(photosModel: photosList[index]),
      itemCount: photosList.length,
    );

///error

'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 649 pos 12: 'targetLastIndex == null || lastIndex <= targetLastIndex': is not true.

**Comment by berkaymazlumlar** [comment]
Is there anything new about this issue?

**Comment by h1amza** [comment]
no unfortunately

**Comment by letsar** [comment]
I think it's related to the issue #232. Which I'll fix today.

**Comment by letsar** [comment]
Fixed in 0.6.2.
