### ISSUE TITLE
* thread #9, name = 'io.flutter.1.ui', stop reason = EXC_BAD_ACCESS (code=257, address=0x12e008041)

### ISSUE THREAD

**Issue by wsb1689** [letsar/flutter_staggered_grid_view#249]
If the waterfall data list slides to a certain number of pages, or the activity is too fast, there will be a problem
code example
SliverMasonryGrid(
        delegate: SliverChildBuilderDelegate((context, index){
          return GestureDetector(
              child: Card(
                elevation: 0,
                child: Container(
                  height: index.isEven ? 300 : 300*3/4,
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Expanded(
                        child: Container(
                            child: ClipRRect(
                              borderRadius: BorderRadius.only(
                                  topLeft: Radius.circular(5),
                                  topRight: Radius.circular(5)),
                              child: Image(
                                image: CachedNetworkImageProvider(pageData[index]
                                ['product']['abbreviateUrl']
                                    .length >
                                    0 &&
                                    pageData[index]['product']['abbreviateUrl']
                                    [0] !=
                                        ''
                                    ? pageData[index]['product']['abbreviateUrl'][0]
                                    : 'http://image.douquan.com/static/product-default.png'),
                                width: double.infinity,
                                height: 150,
                                fit: BoxFit.cover,
                              ),
                            )),
                      ),
                      Container(
                        padding: EdgeInsets.all(10),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          mainAxisAlignment: MainAxisAlignment.start,
                          children: [
                            Text(
                              pageData[index]['product']['productName'] != null
                                  ? pageData[index]['product']['productName']
                                  : '',
                              maxLines: 1,
                              style: TextStyle(
                                color: Color(0xFF101010),
                              ),
                            ),
                            SizedBox(
                              height: 5,
                            ),
                            Text.rich(TextSpan(children: [
                              TextSpan(
                                  text: '￥',
                                  style: TextStyle(
                                      color: Color(0xFFC73E3A),
                                      fontSize: 14,
                                      fontWeight: FontWeight.bold)),
                              TextSpan(
                                text:
                                '${pageData[index]['product']['finalPrice'] != null ? pageData[index]['product']['finalPrice'].toStringAsFixed(0) : ''}',
                                style: TextStyle(
                                    color: Color(0xFFC73E3A),
                                    fontWeight: FontWeight.bold,
                                    fontSize: 18),
                              )
                            ])),
                          ],
                        ),
                      )
                    ],
                  ),
                ),
              ),
              onTap: () {
                UmengCommonSdk.onEvent(
                    "product_tap", {"name": "泉市/${widget.item["customName"]}"});
                Navigator.of(context).pushNamed(RouteName.productDetail,
                    arguments: {
                      "productNo": pageData[index]['product']['productNo']
                    });
              });
        },
          childCount: pageData.length,),
        gridDelegate: SliverSimpleGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2),
      mainAxisSpacing: 10,
      crossAxisSpacing: 10,
    )

* thread #9, name = 'io.flutter.1.ui', stop reason = EXC_BAD_ACCESS (code=257, address=0x12e008041)
    frame #0: 0x000000012e008041
->  0x12e008041: .long  0xdb009601                ; unknown opcode
    0x12e008045: .long  0x41000007                ; unknown opcode
    0x12e008049: .long  0x412e0080                ; unknown opcode
    0x12e00804d: ldr    w0, 0x12e06405d
Target 0: (Runner) stopped.

**Comment by letsar** [comment]
Not sure this is linked to this package. Can you provide a full code sample I could just copy/paste and run please? (and within a code block).

**Comment by letsar** [comment]
Closing since no response since a while.
