### ISSUE TITLE
Tile

### ISSUE THREAD

**Issue by akhilgorantala** [letsar/flutter_staggered_grid_view#251]
Try correcting the name to the name of an existing method, or defining a method named 'Tile'.
        return Tile(
               ^^^^

**Comment by letsar** [comment]
What?

**Comment by mdgb** [comment]
using version 0.6.2 if I use the snippet from the readme 
MasonryGridView.count(
  crossAxisCount: 4,
  mainAxisSpacing: 4,
  crossAxisSpacing: 4,
  itemBuilder: (context, index) {
    return Tile(
      index: index,
      extent: (index % 5 + 1) * 100,
    );
  },
);

the error is 
The method 'Tile' isn't defined for the type 'MasonryTestPage'.
Try correcting the name to the name of an existing method, or defining a method named 'Tile'

**Comment by Helocominc** [comment]
Cannot find `Tile()` in `MasonryGridView.builder()`. 
How can I be able to find the `Tile()` widget inside Masonry? 

I am using the latest version on Android

**Comment by brianllun** [comment]
same problem here. where is the tile class?

**Comment by Helocominc** [comment]
To anyone still facing this issue consider looking at the example app. The `Tile` widget is a customized and not a property in the package

**Comment by letsar** [comment]
Yes it was an example widget, sorry for the confusion

**Comment by S0NN1** [comment]
I wouldn't close this issue since the example must be something working regarding the context, so I highly recommend modifying the example in the README
