### ISSUE TITLE
AlignedGridView.extent: minCrossAxisExtent parameter

### ISSUE THREAD

**Issue by tomaszdrozdz** [letsar/flutter_staggered_grid_view#252]
AlignedGridView.extent()

has parameter:  maxCrossAxisExtent

It would be really nice to have also something like:
minCrossAxisExtent
or alike, so my grid "items" can not "shrink" lower then that.

Also combining maxCrossAxisExtent and minCrossAxisExtent would make effect of fixedCrossAxisExtent,
or perhaps there could be also fixedCrossAxisExtent  (you can set either fixedCrossAxisExtent or any of minCrossAxisExtent, CrossAxisExtent).

Perhaps it could be also done for main axis ?

Please consider if this is possible / doable and worth of implementing ?

What do you think ?

**Comment by letsar** [comment]
Sorry, but I'm not sure to follow. Can you make images of what you would want to achieve?

**Comment by letsar** [comment]
Closing since no response since a while.
