### ISSUE TITLE
Overlay inside CustomScrollView

### ISSUE THREAD

**Issue by appinteractive** [letsar/flutter_staggered_grid_view#259]
Hey, first thanks for that great package! 

I'm using a CustomScrollView with the SliverMasonryGrid inside, now I need a way to Overlay that Sliver with a Widget (full height). How do I achive that? I cant use Stack as it seems but I also did not find any other approach. Can someone give me a gentle hint?

Here a Scribble, the 3th Sliver is the Staggerd Grid View which is "deactivated"

![grafik](https://user-images.githubusercontent.com/432828/177016620-46719a87-9800-411c-9d0d-c5a4d7fdd116.png)

**Comment by letsar** [comment]
Why don't you replace the SliverMasonryGrid upon a condition with your overlay?

**Comment by appinteractive** [comment]
What do you mean with replace? The grid is underneath the overlay. I can't fake it because it's still scrollable. 

I was looking for a way to wrap it with another positioned element but I don't get how. 

I would need to use SliverToBox but then I can't user another sliver inside that. 

What I ended up doing right now is to calculate the position and place the overlay outside the scroll view. 

Any better idea? Do I miss something?

**Comment by letsar** [comment]
Well it doesn't seem related to this package. Maybe a look to https://pub.dev/packages/sliver_tools
