### ISSUE TITLE
The element type 'SliverStaggeredGrid can't be assigned to variable of type widget

### ISSUE THREAD

**Issue by TribalMarks** [letsar/flutter_staggered_grid_view#26]
Am new to flutter and i really want to use  staggered list view, i tried using yours but saw these errors and i don't know how to fix them.
code causing the problem:

slivers: <Widget>[
            new SliverStaggeredGrid.count(
              crossAxisCount: 4,
              mainAxisSpacing: 4.0,
              crossAxisSpacing: 4.0,
              children: const <Widget>[
                const Text('1'),
                const Text('2'),
                const Text('3'),
                const Text('4'),
                const Text('5'),
                const Text('6'),
                const Text('7'),
                const Text('8'),
              ],
              staggeredTiles: const <StaggeredTile>[
                const StaggeredTile.count(2, 2),
                const StaggeredTile.count(2, 1),
                const StaggeredTile.count(2, 2),
                const StaggeredTile.count(2, 1),
                const StaggeredTile.count(2, 2),
                const StaggeredTile.count(2, 1),
                const StaggeredTile.count(2, 2),
                const StaggeredTile.count(2, 1),
              ],
            )

compiler message:
compiler message: file:///C:/Users/Mercy/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_staggered_grid_view-0.2.7/lib/src/widgets/sliver.dart:15:13: Error: Type 'SliverWithKeepAliveWidget' not found.
compiler message:     extends SliverWithKeepAliveWidget {
compiler message:             ^
compiler message: file:///C:/Users/Mercy/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_staggered_grid_view-0.2.7/lib/src/widgets/sliver.dart:92:60: Error: The parameter 'newWidget' of the method 'SliverVariableSizeBoxAdaptorElement::update' has type #lib1::SliverVariableSizeBoxAdaptorWidget, which does not match the corresponding type in the overridden method (#lib2::RenderObjectWidget).
compiler message: Change to a supertype of #lib2::RenderObjectWidget (or, for a covariant parameter, a subtype).
compiler message:   void update(covariant SliverVariableSizeBoxAdaptorWidget newWidget) {
compiler message:                                                            ^
compiler message: file:///C:/Android/Flutter/flutter/packages/flutter/lib/src/widgets/framework.dart: Context: This is the overriden method ('update').
compiler message: file:///C:/Users/Mercy/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_staggered_grid_view-0.2.7/lib/src/widgets/sliver.dart:86:42: Error: The return type of the method 'SliverVariableSizeBoxAdaptorElement::widget' is #lib1::SliverVariableSizeBoxAdaptorWidget, which does not match the return type of the overridden method (#lib2::RenderObjectWidget).
compiler message: Change to a subtype of #lib2::RenderObjectWidget.
compiler message:   SliverVariableSizeBoxAdaptorWidget get widget => super.widget;
compiler message:                                          ^
compiler message: file:///C:/Android/Flutter/flutter/packages/flutter/lib/src/widgets/framework.dart: Context: This is the overriden method ('widget').
compiler message: file:///C:/Users/Mercy/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_staggered_grid_view-0.2.7/lib/src/widgets/sliver.dart:20:14: Error: Constructor has no named parameter with the name 'key'.
compiler message:   }) : super(key: key);
compiler message:              ^^^
compiler message: file:///C:/Users/Mercy/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_staggered_grid_view-0.2.7/lib/src/widgets/sliver.dart:69:11: Error: Superclass has no method named 'debugFillProperties'.
compiler message:     super.debugFillProperties(properties);
compiler message:           ^^^^^^^^^^^^^^^^^^^
compiler message: file:///C:/Users/Mercy/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_staggered_grid_view-0.2.7/lib/src/widgets/sliver.dart:83:15: Error: A value of type '#lib1::SliverVariableSizeBoxAdaptorWidget' can't be assigned to a variable of type '#lib2::RenderObjectWidget'.
compiler message: Try changing the type of the left hand side, or casting the right hand side to '#lib2::RenderObjectWidget'.
compiler message:       : super(widget);
compiler message:               ^
compiler message: file:///C:/Users/Mercy/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_staggered_grid_view-0.2.7/lib/src/widgets/sliver.dart:86:58: Error: A value of type '#lib1::RenderObjectWidget' can't be assigned to a variable of type '#lib2::SliverVariableSizeBoxAdaptorWidget'.
compiler message: Try changing the type of the left hand side, or casting the right hand side to '#lib2::SliverVariableSizeBoxAdaptorWidget'.
compiler message:   SliverVariableSizeBoxAdaptorWidget get widget => super.widget;
compiler message:                                                          ^
compiler message: file:///C:/Users/Mercy/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_staggered_grid_view-0.2.7/lib/src/widgets/sliver.dart:94:18: Error: A value of type '#lib1::SliverVariableSizeBoxAdaptorWidget' can't be assigned to a variable of type '#lib2::RenderObjectWidget'.
compiler message: Try changing the type of the left hand side, or casting the right hand side to '#lib2::RenderObjectWidget'.
compiler message:     super.update(newWidget);
compiler message:                  ^
compiler message: file:///C:/Users/Mercy/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_staggered_grid_view-0.2.7/lib/src/widgets/sliver.dart:293:25: Error: The method 'debugValidateChild' isn't defined for the class '#lib1::RenderSliverVariableSizeBoxAdaptor'.
compiler message: Try correcting the name to the name of an existing method, or defining a method named 'debugValidateChild'.
compiler message:     assert(renderObject.debugValidateChild(child));
compiler message:                         ^
compiler message: file:///C:/Users/Mercy/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_staggered_grid_view-0.2.7/lib/src/widgets/sliver.dart:294:17: Error: The method '[]=' isn't defined for the class '#lib1::RenderSliverVariableSizeBoxAdaptor'.
compiler message: Try correcting the name to the name of an existing method, or defining a method named '[]='.
compiler message:     renderObject[_currentlyUpdatingChildIndex] = child;
compiler message:                 ^
compiler message: file:///C:/Users/Mercy/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_staggered_grid_view-0.2.7/lib/src/widgets/staggered_grid_view.dart:492:16: Error: A value of type '#lib1::SliverStaggeredGrid' can't be assigned to a variable of type '#lib2::Widget'.
compiler message: Try changing the type of the left hand side, or casting the right hand side to '#lib2::Widget'.
compiler message:     return new SliverStaggeredGrid(
compiler message:                ^

**Comment by letsar** [comment]
Hi @TribalMarks , can you post the result of `flutter doctor` please?

**Comment by jitenders859** [comment]
I am also facing the same problem and here is my flutter doctor result.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v0.11.3, on Microsoft Windows [Version 10.0.17134.523], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.1)
[√] IntelliJ IDEA Community Edition (version 2018.2)
[√] VS Code, 64-bit edition (version 1.23.1)
[√] Connected device (1 available)

• No issues found!

**Comment by letsar** [comment]
HI @jitenders859 you need to upgrade flutter. The 1.0 is out now 😃 and the SliverWithKeepAliveWidget has been created in the lasts betas (I don't remember which one).

**Comment by jitenders859** [comment]
hello letsar I am getting this error 
I have two apps with flutter version 0.11.3 with staggeredgridview one app is working fine and other it's giving error
file:///C:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_staggered_grid_view-0.2.7/lib/src/widgets/staggered_grid_view.dart:492:16: Error: A value of type '#lib1::SliverStaggeredGrid' can't be assigned to a variable of type '#lib2::Widget'.
Try changing the type of the left hand side, or casting the right hand side to '#lib2::Widget'.
    return new SliverStaggeredGrid(
               ^
Compiler failed on F:\projects\carejoy\lib\main.dart
Gradle task assembleDebug failed with exit code 1

**Comment by letsar** [comment]
Yeah I used the new widget from 0.2.6.
But the best thing to do it's to upgrade to the 1 0 of Flutter.
