### ISSUE TITLE
aligned grid with cross axis variation

### ISSUE THREAD

**Issue by clragon** [letsar/flutter_staggered_grid_view#266]
If I have understood correctly, the problem with the staggered grid view is that the tiles may not fill the entire cross axis,
and therefore might shift around if new tiles are added which is undesirable. That is why that layout was limited to small item counts.

It would be nice to have a grid view layout in which the items are forced or otherwise guaranteed to always fill the entire cross axis, while also all having the same height in their axis like aligned grid. 

This could be achieved by asserting that they add up to an entire axis or by distributing any remaining space between them or by stretching the last one to fill or there might be other ways to do so.
This wouldnt replicate the full power of a staggered grid, as no gaps are allowed and item height couldnt exceed the current row it is in, but it would probably be easier to layout and avoid the shifting problem.
(I am unsure whether a full staggered grid layout where taking the full cross axis is enforced would be possible.)

Infinite grid layouts like the following seen in the samsung galaxy gallery app could be possible:

![image](https://user-images.githubusercontent.com/11785085/186010305-70687d4f-b8cf-4af1-8afa-eabc603c1eef.png)

**Comment by letsar** [comment]
I'm not sure to understand. Isn't [Quilted](https://github.com/letsar/flutter_staggered_grid_view/wiki/Quilted) what you want ?

**Comment by clragon** [comment]
unfortunately not. 
I would like a grid that behaves like Aligned when measuring height for its items,
but also allows having mixed cross-axis sizes for its children. 

Unlike StaggeredGrid, the children of one row of the grid would always be forced to fully fill the row width 
(this means, no empty spaces and no shuffling around when adding new items).

You can see these features in the image I have sent:
- the items have arbitrary height, but they all have the same height in one row
- there arent always the same amount of items in one row
- the items have different widths inside of a row, instead of being all the same width
