### ISSUE TITLE
How to adjust the height of the components?

### ISSUE THREAD

**Issue by petrovyuri** [letsar/flutter_staggered_grid_view#268]
Hello, can you please tell me how to adjust the height of the components?

https://gist.github.com/petrovyuri/2bc5ca06e5f4ff312d0c691c973e71d4

![image](https://user-images.githubusercontent.com/48598325/189903758-f299b9bf-7d3e-43ba-a3a2-32d4bec0c9ea.png)

**Comment by letsar** [comment]
See https://github.com/letsar/flutter_staggered_grid_view/wiki/Quilted
