### ISSUE TITLE
StaggeredGrid breaks Material.clip within ListView when scrolling

### ISSUE THREAD

**Issue by eEQK** [letsar/flutter_staggered_grid_view#276]
Using a ListView that contains both StaggeredGrid and a Material breaks rendering of the latter.

Material has to have a combination of:
 * clipBehavior set to Clip.hardEdge
 * RoundedRectangleBorder with circular radius and some side (radius, color and width don't matter)
 
 Once you have this setup, simply try scrolling.

Happens only on iOS (both simulator and real device).

```
$ flutter --version
Flutter 3.3.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d9111f6402 (6 days ago) • 2022-10-19 12:27:13 -0700
Engine • revision 3ad69d7be3
Tools • Dart 2.18.2 • DevTools 2.15.0
```

I'm using Flutter 3.3.5 but this issue has been also detected on a 2 month old build (3.3.1 at the time)

Here's a reproducible example: https://gist.github.com/eEQK/e91dc64cd0d2c7de79e23fb194ca6115

https://user-images.githubusercontent.com/15970653/197843760-afb5ce9e-bb21-4f38-bd72-4ef82f9ae2be.mov

**Comment by letsar** [comment]
Clsoing, since this is not an issue with this package. If we remove the `StaggeredGrid`, the issue is the same.
