### ISSUE TITLE
More detailed document

### ISSUE THREAD

**Issue by comeonbuddy** [letsar/flutter_staggered_grid_view#28]
Spent about 30 mins still can't figure out exactly how to configure this, played around with the variables and getting completely random looking results... It would be great to have a more detailed document on CrossAxisCount, variables to pass onto StaggerredTile.fit and StaggeredTile.count.

**Comment by letsar** [comment]
Good point 👍

**Comment by letsar** [comment]
Does the API on latest 0.5.0 preview is easier to use? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
