### ISSUE TITLE
issue with StaggeredGridView.countBuilder() 

### ISSUE THREAD

**Issue by balqeesAldabaybah** [letsar/flutter_staggered_grid_view#29]
I keep getting this error however I use the flutter_staggered_grid_view package. 

The following _CompileTimeError was thrown building StaggeredGridView(scrollDirection: vertical,
I/flutter (17502): primary: using primary controller, AlwaysScrollableScrollPhysics, padding: EdgeInsets.all(8.0),
I/flutter (17502): dirty):
I/flutter (17502): 'package:flutter_staggered_grid_view/src/widgets/staggered_grid_view.dart': error: line 492 pos 16:
I/flutter (17502): file:///C:/Users/Balqees/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_staggered_grid_view-0.2.7/lib/src/widgets/staggered_grid_view.dart:492:16:
I/flutter (17502): Error: A value of type '#lib1::SliverStaggeredGrid' can't be assigned to a variable of type
I/flutter (17502): '#lib2::Widget'.
I/flutter (17502): Try changing the type of the left hand side, or casting the right hand side to '#lib2::Widget'.
I/flutter (17502):     return new SliverStaggeredGrid(
I/flutter (17502):                ^
I/flutter (17502):     return new SliverStaggeredGrid(
I/flutter (17502):                ^

and here is my code: 
I was just trying to test the code snippet in this link: https://pub.dartlang.org/packages/flutter_staggered_grid_view#-readme-tab-
  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      appBar: new AppBar(
        title: new Text('Mad Libs'),
      ),
      body: new StaggeredGridView.countBuilder(
          crossAxisCount: 4,
          itemCount: 8,
          itemBuilder: (BuildContext context, int index) => new Container(
              color: Colors.green,
              child: new Center(
                child: new CircleAvatar(
                  backgroundColor: Colors.white,
                  child: new Text('$index'),
                ),
              )),
          staggeredTileBuilder: (int index) =>
              new StaggeredTile.count(2, index.isEven ? 2 : 1),
          mainAxisSpacing: 4.0,
          crossAxisSpacing: 4.0,
        )
    );
  }

**Comment by jamesblasco** [comment]
Do you still have the issue?
It looks like the package was not added correctly to your flutter project

**Comment by letsar** [comment]
Closing since no response from the OP
