### ISSUE TITLE
Add example with scrollDirection:Axis.horizontal

### ISSUE THREAD

**Issue by KarenKaKa** [letsar/flutter_staggered_grid_view#30]
All examples are vertical，Can you write an example of  scrollDirection: Axis.horizontal

**Comment by pfugwtg** [comment]
There are some problems when scrollDirection is Axis.horizontal: the height of the item is not right

**Comment by pfugwtg** [comment]
I've solved this problem yesterday, which cost me several hours. This is a bug, and the key code is below:
In sliver_staggered_grid.dart,  find the class RenderSliverStaggeredGrid and the line like
`BoxConstraints constraints =
            new BoxConstraints.tightFor(width: geometry.crossAxisExtent);`
You can fix it by set the width `geometry.crossAxisExtent` when `vertical` and `geometry.mainAxisExtent` when `horizontal`.

**Comment by dganzella** [comment]
@pfugwtg you MOTHER FLUTTER! that was it! thanks a lot!

**Comment by sonysm** [comment]
can give an example?

**Comment by letsar** [comment]
The library as been completely rewritten, can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
