### ISSUE TITLE
Error: Method not found: 'Tile' in v0.6.2

### ISSUE THREAD

**Issue by iamdennisisaac** [letsar/flutter_staggered_grid_view#306]
code given in the 'get started' section shows an error
<img width="512" alt="image" src="https://github.com/letsar/flutter_staggered_grid_view/assets/13303482/db03c30a-f78d-468d-9955-df28e3d6178f">

same goes for the flutter package link
https://pub.dev/packages/flutter_staggered_grid_view

**Comment by ankeet7x** [comment]
I'm facing the same issue.

**Comment by KyawNaingTun** [comment]
You can use your own widget instead of Tile. @iamdennisisaac
