### ISSUE TITLE
`crossAxisCellCount` and `mainAxisCellCount` are reversed?

### ISSUE THREAD

**Issue by lukehutch** [letsar/flutter_staggered_grid_view#309]
Using `StaggeredGridTile.count`, if I specify

```dart
              crossAxisCellCount: 1,
              mainAxisCellCount: 2,
```

then I get cells that are twice as tall as they are wide, whereas if I specify

```dart
              crossAxisCellCount: 2,
              mainAxisCellCount: 1,
```

then I get cells that are twice as wide as they are tall.

This seems reversed, since layout is left-to-right, then top-to-bottom -- so the main axis is the horizontal axis.

**Comment by letsar** [comment]
It depends on the axis direction of the scroll. If the scroll is horizontal, then the `mainAxisCellCount` refers to the number of cells in the horizontal axis whereas if the scroll if vertical, then, `mainAxisCellCount` refers to the number of cells in the vertical axis.

**Comment by lukehutch** [comment]
For the example I gave, the scroll direction was vertical.

**Comment by letsar** [comment]
It does not seem reversed to me, if the scroll is vertical and you want a cell that occupies 2 cells in the main axis and 1 cell in the cross axis then you'll get something like the blue cell in the image below.
If you want a cell which occupies 2 cells in the cross axis and 1 cell in the main one, you'll get the green one.
![cell](https://github.com/letsar/flutter_staggered_grid_view/assets/9378033/8d279b76-ce8f-49b8-aca5-521273773fa7)

**Comment by lukehutch** [comment]
Not sure how I kept managing to reverse this in my head. Sorry to take your time on this!

**Comment by burcus** [comment]
@lukehutch It seems I'm late but I'm writing this for those who will struggle this issue like me. StaggeredGrid.count behaves differently depending on it's parent. When you use it directly, mainAxis will be horizontal line. But if you wrap it with ListView your mainAxis will be vertical line. In readme example it's mainAxis is vertical line and crossAxis is horizontal line. So if you wrap your StaggeredGrid with ListView (which has Axis.vertical scroll direction) it will behave as specified in the readme example.
