### ISSUE TITLE
how to get item size, and can add draggable feature?

### ISSUE THREAD

**Issue by Chepond** [letsar/flutter_staggered_grid_view#31]

**Comment by jamesblasco** [comment]
In flutter, there is not straightway to get a widget size.

This article explains very well how to do it. https://medium.com/@diegoveloper/flutter-widget-size-and-position-b0a9ffed9407

Drag and drop is being tracked here https://github.com/letsar/flutter_staggered_grid_view/issues/46

**Comment by qq1023308356** [comment]
You can use https://pub.dev/packages/drag_anim
