### ISSUE TITLE
Hi there, inkwell not working inside staggered_grid_view

### ISSUE THREAD

**Issue by cesarcamps** [letsar/flutter_staggered_grid_view#35]
Hi there, inkwell not working inside staggered_grid_view tile.
This build method
StaggeredGridView.count(
                          crossAxisCount: 4,
                          staggeredTiles: _staggeredTiles,
                          padding: const EdgeInsets.all(10.0),
                          mainAxisSpacing: 10.0,
                          crossAxisSpacing: 10.0,
                          children: _getData(snapshot),
                        );

With this custom widget, i put it inside the grid
Widget build(BuildContext context) {
    return Material(
        elevation: 10.0,
        child: InkResponse(
            child: Container(

And it is not showing ripple effect on tap over the widget.
Thanks by all means :)

**Comment by cesarcamps** [comment]
Sorry this is my flutter doctor
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17763.292], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.31.0)
[√] Connected device (1 available)

• No issues found!

**Comment by jamesblasco** [comment]
It is working for me

```dart

 SliverStaggeredGrid.countBuilder(
              key: ValueKey('value'),
              itemCount: 20,
              crossAxisCount: 5,
              mainAxisSpacing: 20,
              crossAxisSpacing: 10,
              itemBuilder: (BuildContext context, int index) {
                return Material(child: InkResponse(
                  onTap: () {},
                  child: Container(
                  
                  width: 100,
                  height: 100,
                  
                ),),);
              },
              staggeredTileBuilder: (int index) {
                return StaggeredTile.fit(1);
              },
            ),
```

You should add the onTap param to enable the effect. Also, the inside container should not have a color background
