### ISSUE TITLE
The getter 'image' was called on null.

### ISSUE THREAD

**Issue by matte5031** [letsar/flutter_staggered_grid_view#36]
I'm having the issue where it says "The getter 'image' was called on null."

the issue is the exact same like this person https://stackoverflow.com/questions/53679858/the-getter-image-was-called-on-null

It is related to loading images from remote source, all images are fine. It also seems to happen everytime when I have scrolled down and start to scroll up again. Any help or input appreciated, thanks! 

Edit:

seems to happen more often when I have called for more images, for instanse first I call for 20, then I call for 20 more and add them to the list with setstate and update itemcount with all the new images.

**Comment by matte5031** [comment]
I found a workaroud which was to use it inside of a ListView with shrinkWrap: true and primary: false on the StaggeredGridView

**Comment by matte5031** [comment]
I thought I found a workaround, by putting it inside a listview with primary false and shrinkwrap true, however this was a bad idea, it removed the issue above but it will make the device to get out of memory issue for infinite list when reaching 100+ images, atleast for me. So the issue still remains

**Comment by jamesblasco** [comment]
Could you share some reproducible code?
This issue doesn't look to be related to this package itself

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
