### ISSUE TITLE
Is it better to make StaggeredGridView extends CustomScrollView?

### ISSUE THREAD

**Issue by wilin52** [letsar/flutter_staggered_grid_view#37]
In some cases, we need to add a header or a footer into the StaggeredGridView.
StaggeredGridView extends BoxScrollView cannot make it.
I code a CustomBoxScrollView which extends CustomScrollView and copy all the functions from BoxScrollView, it works.

**Comment by wilin52** [comment]
Sorry. I found the answer of it. Use SliverStaggeredGrid in CustomScrollView

**Comment by l-k22** [comment]
> Sorry. I found the answer of it. Use SliverStaggeredGrid in CustomScrollView

Could you share some code? I need to implement headers on both my row and columns (similar to a television schedule).

**Comment by wilin52** [comment]
> > Sorry. I found the answer of it. Use SliverStaggeredGrid in CustomScrollView
> 
> Could you share some code? I need to implement headers on both my row and columns (similar to a television schedule).

Sorry too late to reply. 
![image](https://user-images.githubusercontent.com/9528566/68469705-a9a72280-0255-11ea-9fc3-4bad8cf600e0.png)
