### ISSUE TITLE
Dose not support scroll in StaggeredGridView ?

### ISSUE THREAD

**Issue by jaceshim** [letsar/flutter_staggered_grid_view#38]
```
             StaggeredGridView.countBuilder(
                primary: false,
                crossAxisCount: 4,
                mainAxisSpacing: 4.0,
                crossAxisSpacing: 4.0,
                staggeredTileBuilder: (index) => new StaggeredTile.fit(2),
                itemBuilder: (BuildContext context, int index) {
                  return CounselorCard(state.counselors[index]);
                },
                itemCount: state.counselors.length,
                controller: _scrollController,
              );
```
This is my code that using StaggeredGridView with controller parameter.
but _scrollController dosen't work. 

Is it not support?
or I would like to scroll with StaggeredGridView. 
have a any idea?

Best Regards.

**Comment by Notsfsssf** [comment]
@jaceshim It's support,here is my code
 ` ScrollController _scrollController=new ScrollController();

  @override
  void initState() {
    super.initState();
    _scrollController.addListener(() {
        print("scroll");
      }
    });
  }` then `controller: _scrollController` It's working properly

**Comment by jaceshim** [comment]
@Notsfsssf 
I had a poor understanding of the behavior of scrollControll. Answer Thank you very much.

**Comment by stevenosse** [comment]
> 
> 
> @jaceshim It's support,here is my code
> 
> ```
> ScrollController _scrollController=new ScrollController();
> 
>   @override
>   void initState() {
>     super.initState();
>     _scrollController.addListener(() {
>         print("scroll");
>       }
>     });
>   }
> ```
> 
> then ` controller: _scrollController` It's working properly

Your code seems not to work
here is the fix i've added : 
```
 @override
  void initState() {
    super.initState();
    _scrollController.addListener(() {
      print("scroll");
    });
  }
```
