### ISSUE TITLE
pub get failed (1)

### ISSUE THREAD

**Issue by realcarlos** [letsar/flutter_staggered_grid_view#4]
Running "flutter packages get" in example...                     
Package flutter_staggered_grid_view requires Flutter SDK version ^0.1.0 but the current SDK is 0.2.1-pre.45.
pub get failed (1)

**Comment by letsar** [comment]
I guess you are still in **alpha**. This package is only working for flutter **dev** and **beta** channels.

**Comment by guilhermeof** [comment]
I'm using dev version v0.2.0 and are experiencing the same problem.

**Comment by letsar** [comment]
Oh I misread the version. I will get the latest dev version. Have you an error log?

**Comment by letsar** [comment]
Should be ok now

**Comment by guilhermeof** [comment]
It's ok now
