### ISSUE TITLE
When there was bottomNavigationBar in the layout, the staggered grid view did not calculate the height correctly

### ISSUE THREAD

**Issue by CCY0122** [letsar/flutter_staggered_grid_view#40]
My layout hierarchy looks something like this：
```
Scaffold(
  TabBarView(
    children(
      StaggeredGridView,
      ....
    )
  ),
  bottomNavigationBar(...),
)
```

crossAxisCount is 2,when the itemCount is even number，Layout is correct，
but when the itemCount is odd number，the layout height exceeded the bottomNavigationBar（I'm sure the list has scrolled down to the bottom）.

**screenshot：**
itemCount is odd number:
![image](https://user-images.githubusercontent.com/18615897/54798855-85321200-4c95-11e9-8a1d-e57c7a9129df.png)

itemCount is even number:
![image](https://user-images.githubusercontent.com/18615897/54798786-2a98b600-4c95-11e9-84d1-92b13ab2cf63.png)

when the itemCount is odd number, logCat will print:
![image](https://user-images.githubusercontent.com/18615897/54798947-f1ad1100-4c95-11e9-9a7d-138d381205d9.png)

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
