### ISSUE TITLE
RangeError

### ISSUE THREAD

**Issue by AnhDTN** [letsar/flutter_staggered_grid_view#42]
![Screenshot_20190401-162330](https://user-images.githubusercontent.com/43284656/55317890-a10a9480-549b-11e9-8503-e21d44bf4d4d.png)

**Comment by phpgeek254** [comment]
anyone with a solution to this??

**Comment by YeFei572** [comment]
+1, 是做分页的时候出现的问题吧? 同样碰到了, 使用`scrollController`来监听分页好像不行呢, 我这边目前是这样的:
```dart
@override
  void initState() {
    super.initState();
    _getPosts(_beAdd);
    _scrollController.addListener(() {
      print('cando: ${_scrollController.position.pixels}');
      print('cando: ${_scrollController.position.maxScrollExtent}');

      if (_scrollController.position.pixels ==
          _scrollController.position.maxScrollExtent) {
            print('开始翻页了...............');
        _addMoreData();
      }
    });
  }
```
其中`_scrollController.position.maxScrollExtent`的值 始终是`initify`, 所以没有执行`_addMoreData()`方法. 我判断这边不能使用这个判断条件. 但是目前没有找到解决办法!

**Comment by YeFei572** [comment]
问题已经解决了, 直接上代码吧, 
```dart
 @override
  Widget build(BuildContext context) {
    ScreenUtil.instance = ScreenUtil.getInstance()..init(context);
    return RefreshIndicator(
      onRefresh: _refreshData,
      child: Container(
        color: Colors.grey[100],
        child: StaggeredGridView.countBuilder(
          controller: _scrollController,
          itemCount: posts.length,
          primary: false,
          crossAxisCount: 4,
          mainAxisSpacing: 4.0,
          crossAxisSpacing: 4.0,
          itemBuilder: (context, index) => TileCard(
                img: '${posts[index]['images'][0]}',
                title: '${posts[index]['title']}',
                author: '${posts[index]['userName']}',
                authorUrl: '${posts[index]['iconUrl']}',
                type: '${posts[index]['type']}',
                worksAspectRatio: posts[index]['worksAspectRatio'],
              ),
          staggeredTileBuilder: (index) => StaggeredTile.fit(2),
        ),
      ),
    );
  }
```
你要做的就是在`StaggeredGridView`上面添加一个入参`itemCount`, 这个入参代表你当前列表的长度, 另外还要加上`controller`来监控滑动条的位置, 这样就可以实现分页了!

**Comment by sosite** [comment]
I can confirm that @YeFei572 solution works. So you must remember to include `itemCount` to `StaggeredGridView.builder()`, `StaggeredGridView.countBuilder()` or `StaggeredGridView.extendBuilder()` and if you specify `gridDelegate: SliverStaggeredGridDelegateWithFixedCrossAxisCount` pass items count as `staggeredTileCount` argument.

Btw → @YeFei572 pls, use English next time ;)

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
