### ISSUE TITLE
Drag and drop capability

### ISSUE THREAD

**Issue by dbilgin** [letsar/flutter_staggered_grid_view#46]
I know this is probably a pain to implement, but is there any chance?
Something like [this](https://github.com/iatsu/AndroidDragDropStaggeredGrid).

**Comment by AppleEducate** [comment]
Similar Issue: https://github.com/letsar/flutter_staggered_grid_view/issues/80

Supporting reorder will be a really nice feature.

**Comment by dbilgin** [comment]
Closing this as it's been 3 years with no response
