### ISSUE TITLE
Upgrade to AndroidX

### ISSUE THREAD

**Issue by dereklakin** [letsar/flutter_staggered_grid_view#47]
Great package, but unfortunately not AndroidX compatible. I'll submit a PR to update.

**Comment by BlueskyFR** [comment]
Is it possible to know what AndroidX is please?

**Comment by dereklakin** [comment]
Sorry, I forgot to include the relevant link, which explains why this is a problem: https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

"Android code often uses the android.support libraries to ensure backwards compatibility. The android.support libraries are deprecated, and replaced with AndroidX. AndroidX has feature parity with the old libraries with some additional capabilities but, unfortunately, these two sets of libraries are incompatible."

**Comment by BlueskyFR** [comment]
Okay thanks !

**Comment by letsar** [comment]
Thanks, published in v0.3.0
