### ISSUE TITLE
How to scroll to a specified position?

### ISSUE THREAD

**Issue by wilin52** [letsar/flutter_staggered_grid_view#51]
A problem I met is that I have no idea to scroll staggeredGridView to a specified position. It would be a huge work If calculate offset manually.

Thank you for replying.

**Comment by babaosoftware** [comment]
I'm facing the same problem: bring an item into view by item index. It would be very useful.

**Comment by voivoed** [comment]
Is there a way to scroll if I calculate the offset manually, though? In my case, in the idea I'm working on, the cells all have a fixed height, so it would be easy for me. Scrolling to a specific position is something I really need.

It would really be nice to be able to bring widget index X into view, though.

**Comment by babaosoftware** [comment]
I believe it's possible to scroll to a certain offset, but I didn't try it, because, as @wilin52 mentioned, it's complicated, as my cells might not have the same height, and/or the number of columns might change depending on the screen size/orientation.

**Comment by babaosoftware** [comment]
You can scroll programmatically by attaching a ScrollControler to the grid, and then calling this:
    Timer(
        Duration(milliseconds: 200),
        () => _scrollController.animateTo(_offset,
            duration: const Duration(milliseconds: 500), curve: Curves.ease));
I used a timer in my case, otherwise I get an exception that the ScrollControler is not yet attached. You might not need it.
Give it a try.

**Comment by wilin52** [comment]
the issue can be close , I think .
There is a solution: https://github.com/quire-io/scroll-to-index
 The theory of scroll_to_index is simple, but not effective. The best way to resolve it is that scrollController support scroll to certain index instead of offset like android native .
