### ISSUE TITLE
unusual behaviour while scrolling with new flutter and package update.

### ISSUE THREAD

**Issue by VickySalunkhe** [letsar/flutter_staggered_grid_view#54]
version 0.2.7 was working great, until new flutter update came along,
 version 0.2.7 does not support scrolling anymore, 

Tried version 0.3.0
scrolling is working now but unusual behaviour is there.
lags and refreshes the state randomly and too  quickly.
unpleasant UI behaviour.

Is anyone facing the same issue.

Does anyone know any other way to use staggered view layout ?

**Comment by deathswing** [comment]
same issue

**Comment by apps-transround** [comment]
Item widgets are built and rebuilt while scrolling the staggered grid, of course.
When scrolling a list with 206 item to the end and back 
**v0.2.7** causes **1617** builds.
**v0.3.0** causes **7285**

This can easily result in "unpleasant UI behaviour."  
I just switched back to 0.2.7

**Comment by mutant0113** [comment]
I faced this same issue here.
Somehow I fix it by wrapping the `StaggeredGridView` in `SingleChildScrollView`:
```dart
SingleChildScrollView(
      scrollDirection: Axis.vertical,
      child: StaggeredGridView.countBuilder(
            primary: false,
            ...
      )
)
```
However, I don't really know the root cause.

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
