### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by kmusham** [letsar/flutter_staggered_grid_view#55]
See the error below with the latest version. 

flutter --no-color packages upgrade

The current Flutter SDK version is 1.5.4-hotfix.2.

Because <projectname> depends on flutter_staggered_grid_view >=0.3.0 which requires Flutter SDK version >=1.6.0, version solving failed.

pub upgrade failed (1)
Process finished with exit code 1

**Comment by letsar** [comment]
If you are on stable channel you have to use the previous version which is 0.2.7
