### ISSUE TITLE
Change position of odd item

### ISSUE THREAD

**Issue by nguyenxuankiet262** [letsar/flutter_staggered_grid_view#59]
How can i swap the last odd item position from right side to left side of gridview like this.
https://imgur.com/R32y4uW
My source code:
StaggeredGridView.countBuilder(
.....
 crossAxisCount: 2,
.....
staggeredTileBuilder: (int index) =>
                                new StaggeredTile.fit(1),
)

**Comment by elham-rababah** [comment]
@nguyenxuankiet262  do you found any solution for this ?

**Comment by letsar** [comment]
You can change the textDirection for that but it will also impact all children of the grid.
Also can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
