### ISSUE TITLE
Why am I using this plug at an abnormal height?

### ISSUE THREAD

**Issue by yeoshine** [letsar/flutter_staggered_grid_view#60]
use version:0.2.7
![image](https://user-images.githubusercontent.com/4662777/60646269-81ee1b00-9e6d-11e9-94f6-9dc994190119.png)

This is a random occurrence.

**Comment by yeoshine** [comment]
？

**Comment by zhangweiwei0326** [comment]
下拉加载时跳跃的问题如何解决，如果不固定高度的话

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
