### ISSUE TITLE
flutter升级到1.7.8报如下错

### ISSUE THREAD

**Issue by shaozhiqiang** [letsar/flutter_staggered_grid_view#61]
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'SliverHitTestResult' is not a subtype of type 'BoxHitTestResult'
E/flutter ( 3477): #0      RenderSliverVariableSizeBoxAdaptor.hitTestChildren (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:380:27)
E/flutter ( 3477): #1      RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1279:11)
E/flutter ( 3477): #2      RenderViewportBase.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/viewport.dart:585:24)
E/flutter ( 3477): #3      BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:797:31)
E/flutter ( 3477): #4      BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:725:12)
E/flutter ( 3477): #5      RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:581:33)
E/flutter ( 3477): #6      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2136:11)

**Comment by letsar** [comment]
Can you verify you are on the 0.3.0?

**Comment by shaozhiqiang** [comment]
> Can you verify you are on the 0.3.0?
thks
