### ISSUE TITLE
incompatible with flutter version v1.7.8+hotfix.3

### ISSUE THREAD

**Issue by xenobe** [letsar/flutter_staggered_grid_view#62]
exception as below when I **ontap** the image

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: type 'SliverHitTestResult' is not a subtype of type 'BoxHitTestResult'
#0      RenderSliverVariableSizeBoxAdaptor.hitTestChildren (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:380:27)
#1      RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1279:11)
#2      SliverHitTestResult.addWithAxisOffset (package:flutter/src/rendering/sliver.dart:852:31)
#3      RenderSliverPadding.hitTestChildren (package:flutter/src/rendering/sliver_padding.dart:266:14)
#4      RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1279:11)
#5      RenderViewportBase.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/viewport.dart:585:24)
#6      BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:797:31)
#7      BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:725:12)

#8      RenderViewportBase.hitTestChildren (package:flutter/src/ren<…>
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: type 'SliverHitTestResult' is not a subtype of type 'BoxHitTestResult'
#0      RenderSliverVariableSizeBoxAdaptor.hitTestChildren (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:380:27)
#1      RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1279:11)
#2      SliverHitTestResult.addWithAxisOffset (package:flutter/src/rendering/sliver.dart:852:31)
#3      RenderSliverPadding.hitTestChildren (package:flutter/src/rendering/sliver_padding.dart:266:14)
#4      RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1279:11)
#5      RenderViewportBase.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/viewport.dart:585:24)
#6      BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:797:31)
#7      BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:725:12)

**Comment by letsar** [comment]
Can you verify you are on the 0.3.0?

**Comment by xenobe** [comment]
my bad, 0.3.0 seems fine, I will close this issue.
