### ISSUE TITLE
how to change staggeredTileBuilder responsive

### ISSUE THREAD

**Issue by wisnuwiry** [letsar/flutter_staggered_grid_view#65]
how to adjust the size of staggeredTileBuilder according to the size of the content so the content is not over and not too much space is empty

![Screenshot_20190714-213336_ldolp](https://user-images.githubusercontent.com/44025097/61185109-855c8000-a67f-11e9-8560-57763a599ebe.png)
mode potret

![Screenshot_20190714-213353_ldolp](https://user-images.githubusercontent.com/44025097/61185118-9d340400-a67f-11e9-8123-43dfa5da32c3.png)
mode landscape

my code 

```
StaggeredGridView.countBuilder(
            primary: false,
            crossAxisCount: 4,
            shrinkWrap: true,
            physics: NeverScrollableScrollPhysics(),
            itemCount: document.length,
            itemBuilder: (BuildContext context, int index) {
              return item(context,
                  index: index, title: document[index]['title']);
            },
            crossAxisSpacing: 4.0,
            mainAxisSpacing: 4.0,
            staggeredTileBuilder: (int index) =>
                new StaggeredTile.count(2, index.isEven ? 3 : 2),
          );
```

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
