### ISSUE TITLE
Fix scrolling of multiple Staggered GridView in CustomScrollView

### ISSUE THREAD

**Issue by SohilBhanani** [letsar/flutter_staggered_grid_view#67]
Issue [#14449](https://github.com/flutter/flutter/pull/14449)
I came across a similar issue in GridView as mentioned in the above issue(Bouncy Behaviour, Scrolls to top when reached the bottom), Now, I'm facing the same issue when implementing multiple Staggered GridView inside CustomScrollView.

**Comment by SohilBhanani** [comment]
@akashmi Actually i am trying to implement in collapsing sliver list, So,....

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
