### ISSUE TITLE
Staggered Grid View 0.3.0 doesn't refresh elements 

### ISSUE THREAD

**Issue by Fethi-Hamdani** [letsar/flutter_staggered_grid_view#68]
i have a List of elements that would change Colors on pressed, it doesn't seem to be happening with V 0.3.0 it use to work with older versions, even when i downgraded it didn't work here is my code:
 `  Widget build(BuildContext context) {

    mycolor = new Color(int.parse(
        widget.note.description.split('(0x')[1].split(')')[0],
        radix: 16));

    return Card(
      elevation: 2,
      child: GestureDetector(
        onTap: (){
          setState(() {
          mycolor = Colors.amberAccent;
          });
        },
        child: AnimatedContainer(
          duration: Duration(milliseconds: 400),
          color: mycolor,
          child: forground(),
        ),
      ),
    );
  }`

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
