### ISSUE TITLE
Unhandled Exception: type 'SliverHitTestResult' is not a subtype of type 'BoxHitTestResult'

### ISSUE THREAD

**Issue by MohamedAbd0** [letsar/flutter_staggered_grid_view#69]
Unhandled Exception: type 'SliverHitTestResult' is not a subtype of type 'BoxHitTestResult'

**Comment by Mostafa-SA-developer** [comment]
im also have same issue

**Comment by Mostafa-SA-developer** [comment]
im fixd this issue open the sliver_variable_size_box_adaptor.dart and change this method hitTestChildren to 

**bool hitTestChildren(HitTestResult result,
      {@required double mainAxisPosition, @required double crossAxisPosition}) {
    for (var child in children) {
      if (hitTestBoxChild(BoxHitTestResult.wrap(result), child,
          mainAxisPosition: mainAxisPosition,
          crossAxisPosition: crossAxisPosition)) return true;
    }
    return false;
  }**


after change code start runnig the project the issue must be fixd after fixd go back to code and keep the old code and runnnig you will sen its also working :)

**Comment by xhp281** [comment]
> hitTestChildren

i have same issue ,but this code not valid.

**Comment by xhp281** [comment]
After upgrading to 0.3.0, it's ok.

**Comment by jamesblasco** [comment]
Check https://github.com/letsar/flutter_staggered_grid_view/issues/49
