### ISSUE TITLE
Flutter SDK   version >=0.1.0 <0.3.0, version solving failed.

### ISSUE THREAD

**Issue by anam4nn** [letsar/flutter_staggered_grid_view#7]
Running "flutter packages get" in hello_world...
The current Flutter SDK version is 0.3.1-pre.28.

please update dependencies Flutter SDK version to 0.3.1..

or is any another way for this case..?

**Comment by letsar** [comment]
I removed the Flutter SDK version constraint. Flutter SDK version moves faster than I thought 😄

**Comment by anam4nn** [comment]
Awesome..! Now, time to have fun..!
Thx @letsar .
