### ISSUE TITLE
Can't srcoll inside NestedScrollView

### ISSUE THREAD

**Issue by MinardWu** [letsar/flutter_staggered_grid_view#72]
Can't srcoll inside NestedScrollView

**Comment by cavanlee** [comment]
try it to upgrade version ^0.3.0.

**Comment by dmvvilela** [comment]
Im using 0.3.0 and it does not work.. The scrolls are not linked intrinsically.

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
