### ISSUE TITLE
Aspect ratio of StaggeredGridview.count children not available

### ISSUE THREAD

**Issue by tapizquent** [letsar/flutter_staggered_grid_view#73]
There doesn't seem to be any way you can specify the aspect ratio of children just as in GridView.count. I am trying to achieve certain layout but unfortunately it isn't possible without aspect ratio of children

**Comment by jamesblasco** [comment]
Could you provide a visual example of what you are trying to achieve? 

You can use StaggeredTile.count(1, 2) => The first defines the number of columns for the cell and the second would be the height proportional to the number of columns. In that example, you will have a widget that is double in height than in width. 
Notice that in the second param you can use decimals StaggeredTile.count(1, 0.5)

Also you can use StaggeredTile.fit and inside the itemBuilder use an AspectRatio widget
