### ISSUE TITLE
staggeredTileBuilder random crossAxisCellCount and mainAxisCellCount

### ISSUE THREAD

**Issue by FriendlyNeighbor** [letsar/flutter_staggered_grid_view#75]
When I try to put random numbers inside crossAxisCellCount and mainAxisCellCount, the grid gets destroyed and looks like "regenerating" all the images with random crossAxisCellCount and mainAxisCellCount whenever I scroll. 

Since the new version doesn't accept List<StaggeredTile>,

I would like to know if this is possible. I don't want to set a specific pattern. I want it to refresh everytime the user comes back to that page.

**Comment by jamesblasco** [comment]
Could you provide a reproducible issue of this problem?
