### ISSUE TITLE
Allow to inherit biggest height for all items in same row. (Same for width/column when AxisDirection.horizontal) 

### ISSUE THREAD

**Issue by ninest** [letsar/flutter_staggered_grid_view#76]
Here's an example of what I want to achieve in HTML/CSS: https://codepen.io/themindstorm/pen/BEKBjM

As seen, the second row is taller because the cell on the right has more content

**Comment by simkepal** [comment]
Hey,

Did you maybe managed to do this some other way?

Thanks!

**Comment by themindstorm** [comment]
@simkepal sorry for the late reply, but the answer is no.

Has anyone been able to implement this?

**Comment by letsar** [comment]
The `SliverAlignedGrid` and `AlignedGridView` widgets have been added in the 0.6.0 version to implement this feature 🎉 .
