### ISSUE TITLE
What about Carton's more serious problem?

### ISSUE THREAD

**Issue by aikefang** [letsar/flutter_staggered_grid_view#77]
It's a bit of a carton to use. Look at the number of frames. If you can improve the fluency?

**Comment by pei625569** [comment]
> It's a bit of a carton to use. Look at the number of frames. If you can improve the fluency?

Hi，how do you fix the Carton’s？

**Comment by jamesblasco** [comment]
Performance problem will now be tracked here https://github.com/letsar/flutter_staggered_grid_view/issues/113
