### ISSUE TITLE
Doesn't Work on Web

### ISSUE THREAD

**Issue by xeu100** [letsar/flutter_staggered_grid_view#78]
This doesn't load on web, meaning its just blank.

**Comment by AppleEducate** [comment]
It works for me on web. sidecar.tools

**Comment by jamesblasco** [comment]
Please consider Flutter web is still in beta and not all the features needed could have been implemented. 

As @rodydavis said, it should be working now. 

Feel free to comment here if you still have this problem and if possible provide some reproducible code of the problem you are having.
