### ISSUE TITLE
Unexpected behavior when inside a listview and with a variable crossAxisCount.

### ISSUE THREAD

**Issue by KevinVan720** [letsar/flutter_staggered_grid_view#79]
If you put the staggered grid view inside of a listview, and set the cross axis count to be dependent on phone orientation, there will be weird behaviors... Rotating from portrait mode to landscape mode, the staggered grid view will only occupy the left portion of the screen with the original portrait cross axis count, although the cross axis count has been updated in the parent's build function. 

Snippet of code to reproduce (from the source code of the examples):

ListView(
            shrinkWrap: true,
            children: <Widget>[
              StaggeredGridView.countBuilder(
                shrinkWrap: true,
                physics: ScrollPhysics(),
                crossAxisCount:  MediaQuery.of(context).orientation == Orientation.portrait
                   ? crossAxisCount
                   : crossAxisCount + 4,
                itemCount: tiles.length,
                itemBuilder: _getChild,
                mainAxisSpacing: mainAxisSpacing,
                crossAxisSpacing: crossAxisSpacing,
                padding: padding,
                staggeredTileBuilder: _getStaggeredTile,
              )
            ]);

**Comment by bogdanorzea** [comment]
@KevinVan720 did you find a workaround or fix for this behavior?
