### ISSUE TITLE
Support crossAxisAlignment, start, center, right

### ISSUE THREAD

**Issue by KevinVan720** [letsar/flutter_staggered_grid_view#82]
I know this might now be possible to achieve, but it would really look nice if a child can be aligned differently when there's space around it. Right now a child would always be aligned at the top left even it is the only child in that row/column.

**Comment by jamesblasco** [comment]
Adding a  
``dart
MainAxisAlignment mainAxisAlignment = MainAxisAlignment.start,
CrossAxisAlignment crossAxisAlignment = CrossAxisAlignment.center,
``
 would be awesome and very useful

**Comment by MichalNemec** [comment]
Could you point us atleast to where to edit the code to support this? we could create PR.
Its very much needed. If i have 4 columns and instead of having last item on left side i have it on second column. Its unnatural.
