### ISSUE TITLE
not work scroll

### ISSUE THREAD

**Issue by codigorojo** [letsar/flutter_staggered_grid_view#85]
i try with StaggeredGridView.count but no found

**Comment by codigorojo** [comment]
good idea but not work for me

**Comment by letsar** [comment]
Can you tell me which version of this package you use on which flutter version? If you can provide a standalone example also, it would be better.

**Comment by codigorojo** [comment]
tanks a lot!!!!
It´s now found because I find 0.3.0 version.
Your work is excelent! When I´ll be big I want to be like you!!!! (excuseme
for my bad enghish).
