### ISSUE TITLE
Not scrolling 

### ISSUE THREAD

**Issue by khalidsaleh** [letsar/flutter_staggered_grid_view#87]
I am trying to use StaggeredGridView and SliverStaggerdView ,but both of them not scrolling !!
so please i want the solution for this problem or bug..i dont know what to call it.

**Comment by letsar** [comment]
I ran the example on the last version with Flutter version 1.9.1+hotfix.4 and don't see any issue.
What is the version of StaggeredGridView and what Flutter version do you use?

**Comment by khalidsaleh** [comment]
I have got that exception  " Unhandled Exception: type 'SliverHitTestResult' is not a subtype of type 'BoxHitTestResult' "
but it works for me after upgrading it to 0.3.0 from 0.2.7.
Thank you bro !

**Comment by y-xue92** [comment]
upgrading it to 0.3.0 from 0.2.7.

 staggeredTileBuilder: (index) => StaggeredTile.fit(2),

Sliding is not smooth
How to solve this problem?

**Comment by maoqitian** [comment]
> upgrading it to 0.3.0 from 0.2.7.
> 
> staggeredTileBuilder: (index) => StaggeredTile.fit(2),
> 
> Sliding is not smooth
> How to solve this problem?

I also encountered the same problem

**Comment by jamesblasco** [comment]
Scroll was fixed at 0.3.0, https://github.com/letsar/flutter_staggered_grid_view/issues?q=is%3Aissue+is%3Aclosed

The performance for scrolling is being tracked here https://github.com/letsar/flutter_staggered_grid_view/issues/113
