### ISSUE TITLE
CustomGrid Example

### ISSUE THREAD

**Issue by srishalu** [letsar/flutter_staggered_grid_view#89]
I go through your samples but i cant able to understand what is staggered tiles. By default i have 4 widgets to display in screen. If i add one widget from icon button on the top, then the card should be appear in the screen and therefore now 5 in list. And also if i have Text widget the size should be small. If i have Gauge or chart widget the size should be high. How to achieve this? Is this possible to achieve by using your scenario? I need a example like below image 

![grid](https://user-images.githubusercontent.com/24271317/68920567-a18e3c00-079b-11ea-89bc-28485e01f12f.PNG)

Any help is really appreciated.

Thanks in advance

**Comment by jamesblasco** [comment]
Have you solved your problem?

Improved documentation will be tracked here https://github.com/letsar/flutter_staggered_grid_view/issues/28

**Comment by srishalu** [comment]
No

**Comment by jamesblasco** [comment]
![image](https://user-images.githubusercontent.com/19904063/95674837-112ac800-0bb3-11eb-8950-468437253053.png)

```dart
CustomScrollView(
          
          slivers: <Widget>[
            SliverStaggeredGrid.countBuilder(
              itemCount: 200,
              crossAxisCount: 5,
              mainAxisSpacing: 10,
              crossAxisSpacing: 10,
              itemBuilder: (BuildContext context, int index) {
                return Container(
                  color: Colors.red,
                );
              },
              staggeredTileBuilder: (int index) {
                if (index == 0) return StaggeredTile.count(2, 2);
                if (index == 1) return StaggeredTile.count(3, 3);
                if (index == 2) return StaggeredTile.count(2, 1);
                if (index == 3) return StaggeredTile.count(5, 2);

                return StaggeredTile.fit(1);
              },
            ),
          ])
```
