### ISSUE TITLE
StaggeredTile.fit(1) doesn't work when  => scrollDirection: Axis.horizontal,

### ISSUE THREAD

**Issue by jamesblasco** [letsar/flutter_staggered_grid_view#91]
I am building an horizontal staggered grid view but the widgets doesn't have a fitted width 

```dart
Container(
              height: 60,
              width: double.infinity,
              color: Colors.black12,
              child:  StaggeredGridView.count(
                  padding: EdgeInsets.symmetric(horizontal: 20),
                  primary: false,
                  crossAxisSpacing: 10,
                  mainAxisSpacing: 10,
                  crossAxisCount: 2,
                  scrollDirection: Axis.horizontal,
                  staggeredTiles: BlocProvider.of<CongressBloc>(context)
                      .tags
                      .values
                      .map((tag) => StaggeredTile.fit(1))
                      .toList(),
                  children: BlocProvider.of<CongressBloc>(context)
                      .tags
                      .values
                      .map((tag) => Container(width: 200, child: Tag(data: tag)))
                      .toList()),
```

It looks like this
<img width="303" alt="Sin título 2" src="https://user-images.githubusercontent.com/19904063/69641684-f154e900-1060-11ea-92cd-55a88ca7f49f.png">
If I change the container height from 60 to 120 it would look like this, 
<img width="303" alt="grid 2" src="https://user-images.githubusercontent.com/19904063/69641859-2eb97680-1061-11ea-82b6-737f3d02bd38.png">

I think StaggeredTile.fit(1)  should have a fitted width in Axis.horizontal

**Comment by dganzella** [comment]
same issue :\

**Comment by dganzella** [comment]
answer is on https://github.com/letsar/flutter_staggered_grid_view/issues/30

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by kristoffer-zliide** [comment]
We tested it with version 0.6.1, and it seems to work fine now 👍

**Comment by letsar** [comment]
Closing since it's resolved.
