### ISSUE TITLE
setState() called after dispose(): _AnimationLimiterState#d0653(lifecycle state: defunct, not mounted)

### ISSUE THREAD

**Issue by kw2019ltd** [letsar/flutter_staggered_grid_view#96]
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
setState() called after dispose(): _AnimationLimiterState#d0653(lifecycle state: defunct, not mounted)

This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack: 
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1112:9)
#1      State.setState (package:flutter/src/widgets/framework.dart:1147:6)
#2      _AnimationLimiterState.initState.<anonymous closure> (package:flutter_staggered_animations/src/animation_limiter.dart:45:7)
#3      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#4      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1049:9)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by scheduler library ═════════════════════════════════════════════════
setState() called after dispose(): _AnimationLimiterState#8ea40(lifecycle state: defunct, not mounted)
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by eugenio-tesio** [comment]
I had the same problem and i solved changing the super constructor call order on initState():

Wrong code:

```
@override
  void initState() {
    foo_bar(); // in foo_bar i call setState();
    super.initState(); // state initialization after foo_bar()
  }
```
Right code:

```
@override
  void initState() {
    super.initState();
    foo_bar(); // first call super constructor then foo_bar that contains setState() call
  }
```

**Comment by kw2019ltd** [comment]
Mine is stateless widget

**Comment by jamesblasco** [comment]
If you continue to have this problem, could you provide an example code that reproduces the issue you are having?

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
