### ISSUE TITLE
Cards are not sorted responsively on the web.

### ISSUE THREAD

**Issue by eatis** [letsar/flutter_staggered_grid_view#97]
When only changing the width of the web screen, the card does not rerender responsively.
<img width="612" alt="s1" src="https://user-images.githubusercontent.com/1391901/71506665-3c168a80-28c5-11ea-8f21-b0f523fa16d1.png">
<img width="896" alt="s2" src="https://user-images.githubusercontent.com/1391901/71506666-3caf2100-28c5-11ea-9bc2-aa84203ddd67.png">

**Comment by rasmk** [comment]
On vertical window resize the behavior is wrong too. The cards layout should remain fixed, if height of the window changes. But it is not. For some heights, some cards disappear from the screen. Apparently, a new column is created - invisible, right to the viewport.
I can disclose the hidden column then by resizing the window width, as described by @eatis in OP.

**Comment by jamesblasco** [comment]
Flutter Web is in beta and some things are not ready for production. I am using now Flutter beta 1.23 and the resizing is working as expected

![ezgif com-video-to-gif (9)](https://user-images.githubusercontent.com/19904063/95675262-32d97e80-0bb6-11eb-9bd0-5d5c53655a0e.gif)

**Comment by zihandev** [comment]
Anu updates ? The cards are not displayed in order .

**Comment by josefrvaldes** [comment]
It's happening to me in mobile too. 

This is the code I'm using:

`child: SliverStaggeredGrid.countBuilder(
                      crossAxisCount: 2,
                      itemCount: r.length,
                      mainAxisSpacing: 24,
                      crossAxisSpacing: 16,
                      staggeredTileBuilder: (int index) =>
                          const StaggeredTile.fit(1),
                      itemBuilder: (BuildContext context, int index) {
                        final newspaper = r[index];
                        return GestureDetector(
                          onTap: () => context.pushRoute(
                              WebViewRoute(launchUrl: newspaper.baseUrl!)),
                          child: _Tile(
                            newspaper.thumbnailUrl!,
                            index,
                            title: newspaper.date!.published!.toFormattedDate,
                          ),
                        );
                      },
                    ),`
                    
It's showing two columns and that's what I'm expecting, but as the items have different heights, it shows strange sort behaviours. 


![Screenshot](https://user-images.githubusercontent.com/7542644/119137990-ae9b8380-ba41-11eb-9e7b-1be19f2792cd.png)

As you can see, neither dates nor indexes are sorted correctly in that specific layout.
