### ISSUE TITLE
flutter CustomScrollView scroll bug when using multiple SliverStaggeredGrid

### ISSUE THREAD

**Issue by kim-mini6** [letsar/flutter_staggered_grid_view#98]
Can't scroll when using multiple staggeredgridview

Share my code and screen

Please help me

```dart
    CustomScrollView(
      slivers: <Widget>[
        SliverStaggeredGrid.countBuilder(
          itemCount: 10,
          crossAxisCount: 5,
          mainAxisSpacing: 20,
          crossAxisSpacing: 10,
          itemBuilder: (BuildContext context, int index) {
            return Container(
              width: 100,
              height: 100,
              color: Colors.black,
            );
          },
          staggeredTileBuilder: (int index) {
            return StaggeredTile.fit(1);
          },
        ),
        SliverStaggeredGrid.countBuilder(
          itemCount: 10,
          crossAxisCount: 5,
          mainAxisSpacing: 20,
          crossAxisSpacing: 10,
          itemBuilder: (BuildContext context, int index) {
            return Container(
              width: 100,
              height: 100,
              color: Colors.red,
            );
          },
          staggeredTileBuilder: (int index) {
            return StaggeredTile.fit(1);
          },
        ),
        SliverStaggeredGrid.countBuilder(
          itemCount: 10,
          crossAxisCount: 5,
          mainAxisSpacing: 20,
          crossAxisSpacing: 10,
          itemBuilder: (BuildContext context, int index) {
            return Container(
              width: 100,
              height: 100,
              color: Colors.yellow,
            );
          },
          staggeredTileBuilder: (int index) {
            return StaggeredTile.fit(1);
          },
        ),
        SliverStaggeredGrid.countBuilder(
          itemCount: 10,
          crossAxisCount: 5,
          mainAxisSpacing: 20,
          crossAxisSpacing: 10,
          itemBuilder: (BuildContext context, int index) {
            return Container(
              width: 100,
              height: 100,
              color: Colors.green,
            );
          },
          staggeredTileBuilder: (int index) {
            return StaggeredTile.fit(1);
          },
        ),
        SliverStaggeredGrid.countBuilder(
          itemCount: 10,
          crossAxisCount: 5,
          mainAxisSpacing: 20,
          crossAxisSpacing: 10,
          itemBuilder: (BuildContext context, int index) {
            return Container(
              width: 100,
              height: 100,
              color: Colors.pink,
            );
          },
          staggeredTileBuilder: (int index) {
            return StaggeredTile.fit(1);
          },
        ),
      ],
    );
```

![ezgif-2-9c584575188a](https://user-images.githubusercontent.com/55689271/72046185-32484a80-32fb-11ea-92f5-5a421a96b4bd.gif)

**Comment by jamesblasco** [comment]
I created a project with the reproducible issue 
https://github.com/jamesblasco/staggered_grid_view_examples/tree/issue-98

It looks like the sliver staggered grid doesn't persist the size at some point once it disappears from the top and the CustomScrollView update the scroll extent as if the black cells have an empty size

![ezgif-7-c89575ca2b67](https://user-images.githubusercontent.com/19904063/95655165-a5d6ec80-0b05-11eb-8b72-ad63695f4cfb.gif)

**Comment by Siddharth-Dev** [comment]
I ran into same issue and for now I am managing with an ugly hack.

`child: SizedBox(
        height: (products.length/2 + products.length%2) * 245,
        child: CustomScrollView(
          physics: NeverScrollableScrollPhysics(),
          slivers: [
            SliverStaggeredGrid.countBuilder()])))`

**Comment by bhupijoshi** [comment]
I am having the same issue. Any luck here?

**Comment by amiruljack** [comment]
same

**Comment by amiruljack** [comment]
> I ran into same issue and for now I am managing with an ugly hack.
> 
> `SliverToBoxAdapter(`
> `child: SizedBox(`
> `height: (products.length/2 + products.length%2) * 245,`
> `child: CustomScrollView(`
> `physics: NeverScrollableScrollPhysics(),`
> `slivers: [`
> `SliverStaggeredGrid.countBuilder()])))`

this works. tq

**Comment by wangbaiwang** [comment]
> <img alt="" height="600" src="https://user-images.githubusercontent.com/19904063/95655165-a5d6ec80-0b05-11eb-8b72-ad63695f4cfb.gif"> I created a project with the reproducible issue
> https://github.com/jamesblasco/staggered_grid_view_examples/tree/issue-98
> 
> It looks like the sliver staggered grid doesn't persist the size at some point once it disappears from the top and the CustomScrollView update the scroll extent as if the black cells have an empty size.
> 
> See the scrollbar for reference


Have you found the solution yet?

**Comment by kim-mini6** [comment]
> <img alt="" height="600" src="https://user-images.githubusercontent.com/19904063/95655165-a5d6ec80-0b05-11eb-8b72-ad63695f4cfb.gif">재현 가능한 문제 https://github.com/jamesblasco/staggered_grid_view_examples/tree/issue-98 로 프로젝트를 만들었습니다.
> [](https://github.com/jamesblasco/staggered_grid_view_examples/tree/issue-98)
> 
> 은색 지그재그 격자가 상단에서 사라지고 CustomScrollView가 검정색 셀의 크기가 비어있는 것처럼 스크롤 범위를 업데이트하면 어느 시점에서 크기가 유지되지 않는 것처럼 보입니다.
> 
> 참조는 스크롤바를 참조하십시오.

**Comment by kim-mini6** [comment]
Thank you all for the good answers. I'm currently not using this and I'm usually drawing the screen in wrap!

**Comment by kim-mini6** [comment]
Thank you all for the good answers. I'm currently not using SliverStaggeredGrid and I'm usually drawing the screen in wrap!
